// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yijie/events/v1/agent_session.proto

package eventsv1

import (
	v1 "github.com/36Dge/yijie-contracts/sdks/go/protobuf/yijie/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentSessionState int32

const (
	AgentSessionState_AGENT_SESSION_STATE_UNSPECIFIED AgentSessionState = 0
	AgentSessionState_AGENT_SESSION_STATE_STARTING    AgentSessionState = 1
	AgentSessionState_AGENT_SESSION_STATE_IDLE        AgentSessionState = 2
	AgentSessionState_AGENT_SESSION_STATE_ACTIVE      AgentSessionState = 3
	AgentSessionState_AGENT_SESSION_STATE_FAILED      AgentSessionState = 4
)

// Enum value maps for AgentSessionState.
var (
	AgentSessionState_name = map[int32]string{
		0: "AGENT_SESSION_STATE_UNSPECIFIED",
		1: "AGENT_SESSION_STATE_STARTING",
		2: "AGENT_SESSION_STATE_IDLE",
		3: "AGENT_SESSION_STATE_ACTIVE",
		4: "AGENT_SESSION_STATE_FAILED",
	}
	AgentSessionState_value = map[string]int32{
		"AGENT_SESSION_STATE_UNSPECIFIED": 0,
		"AGENT_SESSION_STATE_STARTING":    1,
		"AGENT_SESSION_STATE_IDLE":        2,
		"AGENT_SESSION_STATE_ACTIVE":      3,
		"AGENT_SESSION_STATE_FAILED":      4,
	}
)

func (x AgentSessionState) Enum() *AgentSessionState {
	p := new(AgentSessionState)
	*p = x
	return p
}

func (x AgentSessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentSessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v1_agent_session_proto_enumTypes[0].Descriptor()
}

func (AgentSessionState) Type() protoreflect.EnumType {
	return &file_yijie_events_v1_agent_session_proto_enumTypes[0]
}

func (x AgentSessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentSessionState.Descriptor instead.
func (AgentSessionState) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{0}
}

type AgentEventType int32

const (
	AgentEventType_AGENT_EVENT_TYPE_UNSPECIFIED              AgentEventType = 0
	AgentEventType_AGENT_EVENT_TYPE_THREAD_STARTED           AgentEventType = 1
	AgentEventType_AGENT_EVENT_TYPE_TURN_STARTED             AgentEventType = 2
	AgentEventType_AGENT_EVENT_TYPE_ITEM_STARTED             AgentEventType = 3
	AgentEventType_AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA AgentEventType = 4
	AgentEventType_AGENT_EVENT_TYPE_ITEM_COMPLETED           AgentEventType = 5
	AgentEventType_AGENT_EVENT_TYPE_TURN_COMPLETED           AgentEventType = 6
	AgentEventType_AGENT_EVENT_TYPE_ERROR                    AgentEventType = 7
	AgentEventType_AGENT_EVENT_TYPE_WARNING                  AgentEventType = 8
)

// Enum value maps for AgentEventType.
var (
	AgentEventType_name = map[int32]string{
		0: "AGENT_EVENT_TYPE_UNSPECIFIED",
		1: "AGENT_EVENT_TYPE_THREAD_STARTED",
		2: "AGENT_EVENT_TYPE_TURN_STARTED",
		3: "AGENT_EVENT_TYPE_ITEM_STARTED",
		4: "AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA",
		5: "AGENT_EVENT_TYPE_ITEM_COMPLETED",
		6: "AGENT_EVENT_TYPE_TURN_COMPLETED",
		7: "AGENT_EVENT_TYPE_ERROR",
		8: "AGENT_EVENT_TYPE_WARNING",
	}
	AgentEventType_value = map[string]int32{
		"AGENT_EVENT_TYPE_UNSPECIFIED":              0,
		"AGENT_EVENT_TYPE_THREAD_STARTED":           1,
		"AGENT_EVENT_TYPE_TURN_STARTED":             2,
		"AGENT_EVENT_TYPE_ITEM_STARTED":             3,
		"AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA": 4,
		"AGENT_EVENT_TYPE_ITEM_COMPLETED":           5,
		"AGENT_EVENT_TYPE_TURN_COMPLETED":           6,
		"AGENT_EVENT_TYPE_ERROR":                    7,
		"AGENT_EVENT_TYPE_WARNING":                  8,
	}
)

func (x AgentEventType) Enum() *AgentEventType {
	p := new(AgentEventType)
	*p = x
	return p
}

func (x AgentEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v1_agent_session_proto_enumTypes[1].Descriptor()
}

func (AgentEventType) Type() protoreflect.EnumType {
	return &file_yijie_events_v1_agent_session_proto_enumTypes[1]
}

func (x AgentEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEventType.Descriptor instead.
func (AgentEventType) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{1}
}

type AgentTurnStatus int32

const (
	AgentTurnStatus_AGENT_TURN_STATUS_UNSPECIFIED AgentTurnStatus = 0
	AgentTurnStatus_AGENT_TURN_STATUS_IN_PROGRESS AgentTurnStatus = 1
	AgentTurnStatus_AGENT_TURN_STATUS_COMPLETED   AgentTurnStatus = 2
	AgentTurnStatus_AGENT_TURN_STATUS_INTERRUPTED AgentTurnStatus = 3
	AgentTurnStatus_AGENT_TURN_STATUS_FAILED      AgentTurnStatus = 4
)

// Enum value maps for AgentTurnStatus.
var (
	AgentTurnStatus_name = map[int32]string{
		0: "AGENT_TURN_STATUS_UNSPECIFIED",
		1: "AGENT_TURN_STATUS_IN_PROGRESS",
		2: "AGENT_TURN_STATUS_COMPLETED",
		3: "AGENT_TURN_STATUS_INTERRUPTED",
		4: "AGENT_TURN_STATUS_FAILED",
	}
	AgentTurnStatus_value = map[string]int32{
		"AGENT_TURN_STATUS_UNSPECIFIED": 0,
		"AGENT_TURN_STATUS_IN_PROGRESS": 1,
		"AGENT_TURN_STATUS_COMPLETED":   2,
		"AGENT_TURN_STATUS_INTERRUPTED": 3,
		"AGENT_TURN_STATUS_FAILED":      4,
	}
)

func (x AgentTurnStatus) Enum() *AgentTurnStatus {
	p := new(AgentTurnStatus)
	*p = x
	return p
}

func (x AgentTurnStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentTurnStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v1_agent_session_proto_enumTypes[2].Descriptor()
}

func (AgentTurnStatus) Type() protoreflect.EnumType {
	return &file_yijie_events_v1_agent_session_proto_enumTypes[2]
}

func (x AgentTurnStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentTurnStatus.Descriptor instead.
func (AgentTurnStatus) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{2}
}

type AgentSession struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentSessionId string                 `protobuf:"bytes,2,opt,name=agent_session_id,json=agentSessionId,proto3" json:"agent_session_id,omitempty"`
	CodexThreadId  string                 `protobuf:"bytes,3,opt,name=codex_thread_id,json=codexThreadId,proto3" json:"codex_thread_id,omitempty"`
	ActiveTurnId   string                 `protobuf:"bytes,4,opt,name=active_turn_id,json=activeTurnId,proto3" json:"active_turn_id,omitempty"`
	State          AgentSessionState      `protobuf:"varint,5,opt,name=state,proto3,enum=yijie.events.v1.AgentSessionState" json:"state,omitempty"`
	Cwd            string                 `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Model          string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	ModelProvider  string                 `protobuf:"bytes,8,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentSession) Reset() {
	*x = AgentSession{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSession) ProtoMessage() {}

func (x *AgentSession) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSession.ProtoReflect.Descriptor instead.
func (*AgentSession) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSession) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentSession) GetAgentSessionId() string {
	if x != nil {
		return x.AgentSessionId
	}
	return ""
}

func (x *AgentSession) GetCodexThreadId() string {
	if x != nil {
		return x.CodexThreadId
	}
	return ""
}

func (x *AgentSession) GetActiveTurnId() string {
	if x != nil {
		return x.ActiveTurnId
	}
	return ""
}

func (x *AgentSession) GetState() AgentSessionState {
	if x != nil {
		return x.State
	}
	return AgentSessionState_AGENT_SESSION_STATE_UNSPECIFIED
}

func (x *AgentSession) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *AgentSession) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentSession) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

func (x *AgentSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AgentSession) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ThreadStartedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ModelProvider string                 `protobuf:"bytes,2,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadStartedPayload) Reset() {
	*x = ThreadStartedPayload{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadStartedPayload) ProtoMessage() {}

func (x *ThreadStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadStartedPayload.ProtoReflect.Descriptor instead.
func (*ThreadStartedPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{1}
}

func (x *ThreadStartedPayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ThreadStartedPayload) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

type TurnLifecyclePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AgentTurnStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=yijie.events.v1.AgentTurnStatus" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnLifecyclePayload) Reset() {
	*x = TurnLifecyclePayload{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnLifecyclePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnLifecyclePayload) ProtoMessage() {}

func (x *TurnLifecyclePayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnLifecyclePayload.ProtoReflect.Descriptor instead.
func (*TurnLifecyclePayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{2}
}

func (x *TurnLifecyclePayload) GetStatus() AgentTurnStatus {
	if x != nil {
		return x.Status
	}
	return AgentTurnStatus_AGENT_TURN_STATUS_UNSPECIFIED
}

func (x *TurnLifecyclePayload) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TurnLifecyclePayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ItemLifecyclePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLifecyclePayload) Reset() {
	*x = ItemLifecyclePayload{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLifecyclePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLifecyclePayload) ProtoMessage() {}

func (x *ItemLifecyclePayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLifecyclePayload.ProtoReflect.Descriptor instead.
func (*ItemLifecyclePayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{3}
}

func (x *ItemLifecyclePayload) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ItemLifecyclePayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AgentMessageDeltaPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageDeltaPayload) Reset() {
	*x = AgentMessageDeltaPayload{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageDeltaPayload) ProtoMessage() {}

func (x *AgentMessageDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageDeltaPayload.ProtoReflect.Descriptor instead.
func (*AgentMessageDeltaPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{4}
}

func (x *AgentMessageDeltaPayload) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type AgentProblemPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WillRetry     bool                   `protobuf:"varint,3,opt,name=will_retry,json=willRetry,proto3" json:"will_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProblemPayload) Reset() {
	*x = AgentProblemPayload{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProblemPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProblemPayload) ProtoMessage() {}

func (x *AgentProblemPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProblemPayload.ProtoReflect.Descriptor instead.
func (*AgentProblemPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{5}
}

func (x *AgentProblemPayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AgentProblemPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentProblemPayload) GetWillRetry() bool {
	if x != nil {
		return x.WillRetry
	}
	return false
}

type AgentSessionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion  uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StreamId       string                 `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Trace          *v1.TraceContext       `protobuf:"bytes,6,opt,name=trace,proto3" json:"trace,omitempty"`
	TaskId         string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentSessionId string                 `protobuf:"bytes,8,opt,name=agent_session_id,json=agentSessionId,proto3" json:"agent_session_id,omitempty"`
	CodexThreadId  string                 `protobuf:"bytes,9,opt,name=codex_thread_id,json=codexThreadId,proto3" json:"codex_thread_id,omitempty"`
	TurnId         string                 `protobuf:"bytes,10,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	ItemId         string                 `protobuf:"bytes,11,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EventType      AgentEventType         `protobuf:"varint,12,opt,name=event_type,json=eventType,proto3,enum=yijie.events.v1.AgentEventType" json:"event_type,omitempty"`
	Terminal       bool                   `protobuf:"varint,13,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentSessionEvent_ThreadStarted
	//	*AgentSessionEvent_TurnStarted
	//	*AgentSessionEvent_ItemStarted
	//	*AgentSessionEvent_AgentMessageDelta
	//	*AgentSessionEvent_ItemCompleted
	//	*AgentSessionEvent_TurnCompleted
	//	*AgentSessionEvent_Error
	//	*AgentSessionEvent_Warning
	Payload       isAgentSessionEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionEvent) Reset() {
	*x = AgentSessionEvent{}
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionEvent) ProtoMessage() {}

func (x *AgentSessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_agent_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionEvent.ProtoReflect.Descriptor instead.
func (*AgentSessionEvent) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_agent_session_proto_rawDescGZIP(), []int{6}
}

func (x *AgentSessionEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AgentSessionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentSessionEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AgentSessionEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AgentSessionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AgentSessionEvent) GetTrace() *v1.TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *AgentSessionEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentSessionEvent) GetAgentSessionId() string {
	if x != nil {
		return x.AgentSessionId
	}
	return ""
}

func (x *AgentSessionEvent) GetCodexThreadId() string {
	if x != nil {
		return x.CodexThreadId
	}
	return ""
}

func (x *AgentSessionEvent) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *AgentSessionEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AgentSessionEvent) GetEventType() AgentEventType {
	if x != nil {
		return x.EventType
	}
	return AgentEventType_AGENT_EVENT_TYPE_UNSPECIFIED
}

func (x *AgentSessionEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *AgentSessionEvent) GetPayload() isAgentSessionEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentSessionEvent) GetThreadStarted() *ThreadStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ThreadStarted); ok {
			return x.ThreadStarted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetTurnStarted() *TurnLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_TurnStarted); ok {
			return x.TurnStarted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetItemStarted() *ItemLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ItemStarted); ok {
			return x.ItemStarted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetAgentMessageDelta() *AgentMessageDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_AgentMessageDelta); ok {
			return x.AgentMessageDelta
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetItemCompleted() *ItemLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ItemCompleted); ok {
			return x.ItemCompleted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetTurnCompleted() *TurnLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_TurnCompleted); ok {
			return x.TurnCompleted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetError() *AgentProblemPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetWarning() *AgentProblemPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_Warning); ok {
			return x.Warning
		}
	}
	return nil
}

type isAgentSessionEvent_Payload interface {
	isAgentSessionEvent_Payload()
}

type AgentSessionEvent_ThreadStarted struct {
	ThreadStarted *ThreadStartedPayload `protobuf:"bytes,20,opt,name=thread_started,json=threadStarted,proto3,oneof"`
}

type AgentSessionEvent_TurnStarted struct {
	TurnStarted *TurnLifecyclePayload `protobuf:"bytes,21,opt,name=turn_started,json=turnStarted,proto3,oneof"`
}

type AgentSessionEvent_ItemStarted struct {
	ItemStarted *ItemLifecyclePayload `protobuf:"bytes,22,opt,name=item_started,json=itemStarted,proto3,oneof"`
}

type AgentSessionEvent_AgentMessageDelta struct {
	AgentMessageDelta *AgentMessageDeltaPayload `protobuf:"bytes,23,opt,name=agent_message_delta,json=agentMessageDelta,proto3,oneof"`
}

type AgentSessionEvent_ItemCompleted struct {
	ItemCompleted *ItemLifecyclePayload `protobuf:"bytes,24,opt,name=item_completed,json=itemCompleted,proto3,oneof"`
}

type AgentSessionEvent_TurnCompleted struct {
	TurnCompleted *TurnLifecyclePayload `protobuf:"bytes,25,opt,name=turn_completed,json=turnCompleted,proto3,oneof"`
}

type AgentSessionEvent_Error struct {
	Error *AgentProblemPayload `protobuf:"bytes,26,opt,name=error,proto3,oneof"`
}

type AgentSessionEvent_Warning struct {
	Warning *AgentProblemPayload `protobuf:"bytes,27,opt,name=warning,proto3,oneof"`
}

func (*AgentSessionEvent_ThreadStarted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_TurnStarted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_ItemStarted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_AgentMessageDelta) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_ItemCompleted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_TurnCompleted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_Error) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_Warning) isAgentSessionEvent_Payload() {}

var File_yijie_events_v1_agent_session_proto protoreflect.FileDescriptor

const file_yijie_events_v1_agent_session_proto_rawDesc = "" +
	"\n" +
	"#yijie/events/v1/agent_session.proto\x12\x0fyijie.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cyijie/common/v1/common.proto\"\x9e\x03\n" +
	"\fAgentSession\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\x10agent_session_id\x18\x02 \x01(\tR\x0eagentSessionId\x12&\n" +
	"\x0fcodex_thread_id\x18\x03 \x01(\tR\rcodexThreadId\x12$\n" +
	"\x0eactive_turn_id\x18\x04 \x01(\tR\factiveTurnId\x128\n" +
	"\x05state\x18\x05 \x01(\x0e2\".yijie.events.v1.AgentSessionStateR\x05state\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12%\n" +
	"\x0emodel_provider\x18\b \x01(\tR\rmodelProvider\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"S\n" +
	"\x14ThreadStartedPayload\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12%\n" +
	"\x0emodel_provider\x18\x02 \x01(\tR\rmodelProvider\"\x94\x01\n" +
	"\x14TurnLifecyclePayload\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .yijie.events.v1.AgentTurnStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"G\n" +
	"\x14ItemLifecyclePayload\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"0\n" +
	"\x18AgentMessageDeltaPayload\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\"b\n" +
	"\x13AgentProblemPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"will_retry\x18\x03 \x01(\bR\twillRetry\"\xe9\b\n" +
	"\x11AgentSessionEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x123\n" +
	"\x05trace\x18\x06 \x01(\v2\x1d.yijie.common.v1.TraceContextR\x05trace\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12(\n" +
	"\x10agent_session_id\x18\b \x01(\tR\x0eagentSessionId\x12&\n" +
	"\x0fcodex_thread_id\x18\t \x01(\tR\rcodexThreadId\x12\x17\n" +
	"\aturn_id\x18\n" +
	" \x01(\tR\x06turnId\x12\x17\n" +
	"\aitem_id\x18\v \x01(\tR\x06itemId\x12>\n" +
	"\n" +
	"event_type\x18\f \x01(\x0e2\x1f.yijie.events.v1.AgentEventTypeR\teventType\x12\x1a\n" +
	"\bterminal\x18\r \x01(\bR\bterminal\x12N\n" +
	"\x0ethread_started\x18\x14 \x01(\v2%.yijie.events.v1.ThreadStartedPayloadH\x00R\rthreadStarted\x12J\n" +
	"\fturn_started\x18\x15 \x01(\v2%.yijie.events.v1.TurnLifecyclePayloadH\x00R\vturnStarted\x12J\n" +
	"\fitem_started\x18\x16 \x01(\v2%.yijie.events.v1.ItemLifecyclePayloadH\x00R\vitemStarted\x12[\n" +
	"\x13agent_message_delta\x18\x17 \x01(\v2).yijie.events.v1.AgentMessageDeltaPayloadH\x00R\x11agentMessageDelta\x12N\n" +
	"\x0eitem_completed\x18\x18 \x01(\v2%.yijie.events.v1.ItemLifecyclePayloadH\x00R\ritemCompleted\x12N\n" +
	"\x0eturn_completed\x18\x19 \x01(\v2%.yijie.events.v1.TurnLifecyclePayloadH\x00R\rturnCompleted\x12<\n" +
	"\x05error\x18\x1a \x01(\v2$.yijie.events.v1.AgentProblemPayloadH\x00R\x05error\x12@\n" +
	"\awarning\x18\x1b \x01(\v2$.yijie.events.v1.AgentProblemPayloadH\x00R\awarningB\t\n" +
	"\apayload*\xb8\x01\n" +
	"\x11AgentSessionState\x12#\n" +
	"\x1fAGENT_SESSION_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cAGENT_SESSION_STATE_STARTING\x10\x01\x12\x1c\n" +
	"\x18AGENT_SESSION_STATE_IDLE\x10\x02\x12\x1e\n" +
	"\x1aAGENT_SESSION_STATE_ACTIVE\x10\x03\x12\x1e\n" +
	"\x1aAGENT_SESSION_STATE_FAILED\x10\x04*\xd0\x02\n" +
	"\x0eAgentEventType\x12 \n" +
	"\x1cAGENT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fAGENT_EVENT_TYPE_THREAD_STARTED\x10\x01\x12!\n" +
	"\x1dAGENT_EVENT_TYPE_TURN_STARTED\x10\x02\x12!\n" +
	"\x1dAGENT_EVENT_TYPE_ITEM_STARTED\x10\x03\x12-\n" +
	")AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA\x10\x04\x12#\n" +
	"\x1fAGENT_EVENT_TYPE_ITEM_COMPLETED\x10\x05\x12#\n" +
	"\x1fAGENT_EVENT_TYPE_TURN_COMPLETED\x10\x06\x12\x1a\n" +
	"\x16AGENT_EVENT_TYPE_ERROR\x10\a\x12\x1c\n" +
	"\x18AGENT_EVENT_TYPE_WARNING\x10\b*\xb9\x01\n" +
	"\x0fAgentTurnStatus\x12!\n" +
	"\x1dAGENT_TURN_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGENT_TURN_STATUS_IN_PROGRESS\x10\x01\x12\x1f\n" +
	"\x1bAGENT_TURN_STATUS_COMPLETED\x10\x02\x12!\n" +
	"\x1dAGENT_TURN_STATUS_INTERRUPTED\x10\x03\x12\x1c\n" +
	"\x18AGENT_TURN_STATUS_FAILED\x10\x04BLZJgithub.com/36Dge/yijie-contracts/sdks/go/protobuf/yijie/events/v1;eventsv1b\x06proto3"

var (
	file_yijie_events_v1_agent_session_proto_rawDescOnce sync.Once
	file_yijie_events_v1_agent_session_proto_rawDescData []byte
)

func file_yijie_events_v1_agent_session_proto_rawDescGZIP() []byte {
	file_yijie_events_v1_agent_session_proto_rawDescOnce.Do(func() {
		file_yijie_events_v1_agent_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yijie_events_v1_agent_session_proto_rawDesc), len(file_yijie_events_v1_agent_session_proto_rawDesc)))
	})
	return file_yijie_events_v1_agent_session_proto_rawDescData
}

var file_yijie_events_v1_agent_session_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_yijie_events_v1_agent_session_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_yijie_events_v1_agent_session_proto_goTypes = []any{
	(AgentSessionState)(0),           // 0: yijie.events.v1.AgentSessionState
	(AgentEventType)(0),              // 1: yijie.events.v1.AgentEventType
	(AgentTurnStatus)(0),             // 2: yijie.events.v1.AgentTurnStatus
	(*AgentSession)(nil),             // 3: yijie.events.v1.AgentSession
	(*ThreadStartedPayload)(nil),     // 4: yijie.events.v1.ThreadStartedPayload
	(*TurnLifecyclePayload)(nil),     // 5: yijie.events.v1.TurnLifecyclePayload
	(*ItemLifecyclePayload)(nil),     // 6: yijie.events.v1.ItemLifecyclePayload
	(*AgentMessageDeltaPayload)(nil), // 7: yijie.events.v1.AgentMessageDeltaPayload
	(*AgentProblemPayload)(nil),      // 8: yijie.events.v1.AgentProblemPayload
	(*AgentSessionEvent)(nil),        // 9: yijie.events.v1.AgentSessionEvent
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
	(*v1.TraceContext)(nil),          // 11: yijie.common.v1.TraceContext
}
var file_yijie_events_v1_agent_session_proto_depIdxs = []int32{
	0,  // 0: yijie.events.v1.AgentSession.state:type_name -> yijie.events.v1.AgentSessionState
	10, // 1: yijie.events.v1.AgentSession.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: yijie.events.v1.AgentSession.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 3: yijie.events.v1.TurnLifecyclePayload.status:type_name -> yijie.events.v1.AgentTurnStatus
	10, // 4: yijie.events.v1.AgentSessionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 5: yijie.events.v1.AgentSessionEvent.trace:type_name -> yijie.common.v1.TraceContext
	1,  // 6: yijie.events.v1.AgentSessionEvent.event_type:type_name -> yijie.events.v1.AgentEventType
	4,  // 7: yijie.events.v1.AgentSessionEvent.thread_started:type_name -> yijie.events.v1.ThreadStartedPayload
	5,  // 8: yijie.events.v1.AgentSessionEvent.turn_started:type_name -> yijie.events.v1.TurnLifecyclePayload
	6,  // 9: yijie.events.v1.AgentSessionEvent.item_started:type_name -> yijie.events.v1.ItemLifecyclePayload
	7,  // 10: yijie.events.v1.AgentSessionEvent.agent_message_delta:type_name -> yijie.events.v1.AgentMessageDeltaPayload
	6,  // 11: yijie.events.v1.AgentSessionEvent.item_completed:type_name -> yijie.events.v1.ItemLifecyclePayload
	5,  // 12: yijie.events.v1.AgentSessionEvent.turn_completed:type_name -> yijie.events.v1.TurnLifecyclePayload
	8,  // 13: yijie.events.v1.AgentSessionEvent.error:type_name -> yijie.events.v1.AgentProblemPayload
	8,  // 14: yijie.events.v1.AgentSessionEvent.warning:type_name -> yijie.events.v1.AgentProblemPayload
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_yijie_events_v1_agent_session_proto_init() }
func file_yijie_events_v1_agent_session_proto_init() {
	if File_yijie_events_v1_agent_session_proto != nil {
		return
	}
	file_yijie_events_v1_agent_session_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentSessionEvent_ThreadStarted)(nil),
		(*AgentSessionEvent_TurnStarted)(nil),
		(*AgentSessionEvent_ItemStarted)(nil),
		(*AgentSessionEvent_AgentMessageDelta)(nil),
		(*AgentSessionEvent_ItemCompleted)(nil),
		(*AgentSessionEvent_TurnCompleted)(nil),
		(*AgentSessionEvent_Error)(nil),
		(*AgentSessionEvent_Warning)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yijie_events_v1_agent_session_proto_rawDesc), len(file_yijie_events_v1_agent_session_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yijie_events_v1_agent_session_proto_goTypes,
		DependencyIndexes: file_yijie_events_v1_agent_session_proto_depIdxs,
		EnumInfos:         file_yijie_events_v1_agent_session_proto_enumTypes,
		MessageInfos:      file_yijie_events_v1_agent_session_proto_msgTypes,
	}.Build()
	File_yijie_events_v1_agent_session_proto = out.File
	file_yijie_events_v1_agent_session_proto_goTypes = nil
	file_yijie_events_v1_agent_session_proto_depIdxs = nil
}
