// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yijie/events/v1/task.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED      TaskStatus = 0
	TaskStatus_TASK_STATUS_DRAFT            TaskStatus = 1
	TaskStatus_TASK_STATUS_RUNNING          TaskStatus = 2
	TaskStatus_TASK_STATUS_WAITING_APPROVAL TaskStatus = 3
	TaskStatus_TASK_STATUS_COMPLETED        TaskStatus = 4
	TaskStatus_TASK_STATUS_FAILED           TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_DRAFT",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_WAITING_APPROVAL",
		4: "TASK_STATUS_COMPLETED",
		5: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":      0,
		"TASK_STATUS_DRAFT":            1,
		"TASK_STATUS_RUNNING":          2,
		"TASK_STATUS_WAITING_APPROVAL": 3,
		"TASK_STATUS_COMPLETED":        4,
		"TASK_STATUS_FAILED":           5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v1_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_yijie_events_v1_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v1_task_proto_rawDescGZIP(), []int{0}
}

type TaskEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentSessionId string                 `protobuf:"bytes,2,opt,name=agent_session_id,json=agentSessionId,proto3" json:"agent_session_id,omitempty"`
	CodexThreadId  string                 `protobuf:"bytes,3,opt,name=codex_thread_id,json=codexThreadId,proto3" json:"codex_thread_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode     TaskStatus             `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3,enum=yijie.events.v1.TaskStatus" json:"status_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_yijie_events_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_yijie_events_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEvent) GetAgentSessionId() string {
	if x != nil {
		return x.AgentSessionId
	}
	return ""
}

func (x *TaskEvent) GetCodexThreadId() string {
	if x != nil {
		return x.CodexThreadId
	}
	return ""
}

func (x *TaskEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskEvent) GetStatusCode() TaskStatus {
	if x != nil {
		return x.StatusCode
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

var File_yijie_events_v1_task_proto protoreflect.FileDescriptor

const file_yijie_events_v1_task_proto_rawDesc = "" +
	"\n" +
	"\x1ayijie/events/v1/task.proto\x12\x0fyijie.events.v1\"\xcc\x01\n" +
	"\tTaskEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\x10agent_session_id\x18\x02 \x01(\tR\x0eagentSessionId\x12&\n" +
	"\x0fcodex_thread_id\x18\x03 \x01(\tR\rcodexThreadId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12<\n" +
	"\vstatus_code\x18\x05 \x01(\x0e2\x1b.yijie.events.v1.TaskStatusR\n" +
	"statusCode*\xae\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_STATUS_DRAFT\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12 \n" +
	"\x1cTASK_STATUS_WAITING_APPROVAL\x10\x03\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x05BLZJgithub.com/36Dge/yijie-contracts/sdks/go/protobuf/yijie/events/v1;eventsv1b\x06proto3"

var (
	file_yijie_events_v1_task_proto_rawDescOnce sync.Once
	file_yijie_events_v1_task_proto_rawDescData []byte
)

func file_yijie_events_v1_task_proto_rawDescGZIP() []byte {
	file_yijie_events_v1_task_proto_rawDescOnce.Do(func() {
		file_yijie_events_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yijie_events_v1_task_proto_rawDesc), len(file_yijie_events_v1_task_proto_rawDesc)))
	})
	return file_yijie_events_v1_task_proto_rawDescData
}

var file_yijie_events_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yijie_events_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yijie_events_v1_task_proto_goTypes = []any{
	(TaskStatus)(0),   // 0: yijie.events.v1.TaskStatus
	(*TaskEvent)(nil), // 1: yijie.events.v1.TaskEvent
}
var file_yijie_events_v1_task_proto_depIdxs = []int32{
	0, // 0: yijie.events.v1.TaskEvent.status_code:type_name -> yijie.events.v1.TaskStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yijie_events_v1_task_proto_init() }
func file_yijie_events_v1_task_proto_init() {
	if File_yijie_events_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yijie_events_v1_task_proto_rawDesc), len(file_yijie_events_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yijie_events_v1_task_proto_goTypes,
		DependencyIndexes: file_yijie_events_v1_task_proto_depIdxs,
		EnumInfos:         file_yijie_events_v1_task_proto_enumTypes,
		MessageInfos:      file_yijie_events_v1_task_proto_msgTypes,
	}.Build()
	File_yijie_events_v1_task_proto = out.File
	file_yijie_events_v1_task_proto_goTypes = nil
	file_yijie_events_v1_task_proto_depIdxs = nil
}
