// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file yijie/common/v1/common.proto (package yijie.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file yijie/common/v1/common.proto.
 */
export const file_yijie_common_v1_common: GenFile = /*@__PURE__*/
  fileDesc("Chx5aWppZS9jb21tb24vdjEvY29tbW9uLnByb3RvEg95aWppZS5jb21tb24udjEiWAoMVHJhY2VDb250ZXh0EhAKCHRyYWNlX2lkGAEgASgJEhIKCnJlcXVlc3RfaWQYAiABKAkSEQoJdGVuYW50X2lkGAMgASgJEg8KB3VzZXJfaWQYBCABKAlCTFpKZ2l0aHViLmNvbS8zNkRnZS95aWppZS1jb250cmFjdHMvc2Rrcy9nby9wcm90b2J1Zi95aWppZS9jb21tb24vdjE7Y29tbW9udjFiBnByb3RvMw");

/**
 * @generated from message yijie.common.v1.TraceContext
 */
export type TraceContext = Message<"yijie.common.v1.TraceContext"> & {
  /**
   * @generated from field: string trace_id = 1;
   */
  traceId: string;

  /**
   * @generated from field: string request_id = 2;
   */
  requestId: string;

  /**
   * @generated from field: string tenant_id = 3;
   */
  tenantId: string;

  /**
   * @generated from field: string user_id = 4;
   */
  userId: string;
};

/**
 * Describes the message yijie.common.v1.TraceContext.
 * Use `create(TraceContextSchema)` to create a new message.
 */
export const TraceContextSchema: GenMessage<TraceContext> = /*@__PURE__*/
  messageDesc(file_yijie_common_v1_common, 0);

