// Package nativeconversationv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package nativeconversationv2

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	LocalBearerScopes localBearerContextKey = "LocalBearer.Scopes"
)

// Defines values for NativeErrorAvailability.
const (
	NativeErrorAvailabilityPartial     NativeErrorAvailability = "partial"
	NativeErrorAvailabilityUnavailable NativeErrorAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the NativeErrorAvailability enum.
func (e NativeErrorAvailability) Valid() bool {
	switch e {
	case NativeErrorAvailabilityPartial:
		return true
	case NativeErrorAvailabilityUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for NativeErrorCodexErrorInfo.
const (
	ActiveTurnNotSteerable         NativeErrorCodexErrorInfo = "activeTurnNotSteerable"
	BadRequest                     NativeErrorCodexErrorInfo = "badRequest"
	ContextWindowExceeded          NativeErrorCodexErrorInfo = "contextWindowExceeded"
	CyberPolicy                    NativeErrorCodexErrorInfo = "cyberPolicy"
	HttpConnectionFailed           NativeErrorCodexErrorInfo = "httpConnectionFailed"
	InternalServerError            NativeErrorCodexErrorInfo = "internalServerError"
	Other                          NativeErrorCodexErrorInfo = "other"
	ResponseStreamConnectionFailed NativeErrorCodexErrorInfo = "responseStreamConnectionFailed"
	ResponseStreamDisconnected     NativeErrorCodexErrorInfo = "responseStreamDisconnected"
	ResponseTooManyFailedAttempts  NativeErrorCodexErrorInfo = "responseTooManyFailedAttempts"
	SandboxError                   NativeErrorCodexErrorInfo = "sandboxError"
	ServerOverloaded               NativeErrorCodexErrorInfo = "serverOverloaded"
	SessionBudgetExceeded          NativeErrorCodexErrorInfo = "sessionBudgetExceeded"
	ThreadRollbackFailed           NativeErrorCodexErrorInfo = "threadRollbackFailed"
	Unauthorized                   NativeErrorCodexErrorInfo = "unauthorized"
	UsageLimitExceeded             NativeErrorCodexErrorInfo = "usageLimitExceeded"
)

// Valid indicates whether the value is a known member of the NativeErrorCodexErrorInfo enum.
func (e NativeErrorCodexErrorInfo) Valid() bool {
	switch e {
	case ActiveTurnNotSteerable:
		return true
	case BadRequest:
		return true
	case ContextWindowExceeded:
		return true
	case CyberPolicy:
		return true
	case HttpConnectionFailed:
		return true
	case InternalServerError:
		return true
	case Other:
		return true
	case ResponseStreamConnectionFailed:
		return true
	case ResponseStreamDisconnected:
		return true
	case ResponseTooManyFailedAttempts:
		return true
	case SandboxError:
		return true
	case ServerOverloaded:
		return true
	case SessionBudgetExceeded:
		return true
	case ThreadRollbackFailed:
		return true
	case Unauthorized:
		return true
	case UsageLimitExceeded:
		return true
	default:
		return false
	}
}

// Defines values for NativeEventEventType.
const (
	NativeEventEventTypeNativeNotification NativeEventEventType = "native.notification"
)

// Valid indicates whether the value is a known member of the NativeEventEventType enum.
func (e NativeEventEventType) Valid() bool {
	switch e {
	case NativeEventEventTypeNativeNotification:
		return true
	default:
		return false
	}
}

// Defines values for NativeEventSchemaVersion.
const (
	N8 NativeEventSchemaVersion = 8
)

// Valid indicates whether the value is a known member of the NativeEventSchemaVersion enum.
func (e NativeEventSchemaVersion) Valid() bool {
	switch e {
	case N8:
		return true
	default:
		return false
	}
}

// Defines values for NativeItemAvailability.
const (
	NativeItemAvailabilityAvailable   NativeItemAvailability = "available"
	NativeItemAvailabilityPartial     NativeItemAvailability = "partial"
	NativeItemAvailabilityUnavailable NativeItemAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the NativeItemAvailability enum.
func (e NativeItemAvailability) Valid() bool {
	switch e {
	case NativeItemAvailabilityAvailable:
		return true
	case NativeItemAvailabilityPartial:
		return true
	case NativeItemAvailabilityUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for NativeItemPhase.
const (
	Commentary  NativeItemPhase = "commentary"
	FinalAnswer NativeItemPhase = "final_answer"
)

// Valid indicates whether the value is a known member of the NativeItemPhase enum.
func (e NativeItemPhase) Valid() bool {
	switch e {
	case Commentary:
		return true
	case FinalAnswer:
		return true
	default:
		return false
	}
}

// Defines values for NativeItemStatus.
const (
	NativeItemStatusCompleted  NativeItemStatus = "completed"
	NativeItemStatusDeclined   NativeItemStatus = "declined"
	NativeItemStatusFailed     NativeItemStatus = "failed"
	NativeItemStatusInProgress NativeItemStatus = "inProgress"
)

// Valid indicates whether the value is a known member of the NativeItemStatus enum.
func (e NativeItemStatus) Valid() bool {
	switch e {
	case NativeItemStatusCompleted:
		return true
	case NativeItemStatusDeclined:
		return true
	case NativeItemStatusFailed:
		return true
	case NativeItemStatusInProgress:
		return true
	default:
		return false
	}
}

// Defines values for NativeItemType.
const (
	AgentMessage     NativeItemType = "agentMessage"
	CommandExecution NativeItemType = "commandExecution"
	McpToolCall      NativeItemType = "mcpToolCall"
	Reasoning        NativeItemType = "reasoning"
	Unknown          NativeItemType = "unknown"
	UserMessage      NativeItemType = "userMessage"
)

// Valid indicates whether the value is a known member of the NativeItemType enum.
func (e NativeItemType) Valid() bool {
	switch e {
	case AgentMessage:
		return true
	case CommandExecution:
		return true
	case McpToolCall:
		return true
	case Reasoning:
		return true
	case Unknown:
		return true
	case UserMessage:
		return true
	default:
		return false
	}
}

// Defines values for NativeMcpDisplayDiagnostics.
const (
	ArgumentsUnavailable NativeMcpDisplayDiagnostics = "arguments_unavailable"
	ContentLimit         NativeMcpDisplayDiagnostics = "content_limit"
	ContentRedacted      NativeMcpDisplayDiagnostics = "content_redacted"
	ContentTruncated     NativeMcpDisplayDiagnostics = "content_truncated"
	DisplayLimit         NativeMcpDisplayDiagnostics = "display_limit"
	IdentityUnavailable  NativeMcpDisplayDiagnostics = "identity_unavailable"
	ResultUnavailable    NativeMcpDisplayDiagnostics = "result_unavailable"
	UnsupportedContent   NativeMcpDisplayDiagnostics = "unsupported_content"
)

// Valid indicates whether the value is a known member of the NativeMcpDisplayDiagnostics enum.
func (e NativeMcpDisplayDiagnostics) Valid() bool {
	switch e {
	case ArgumentsUnavailable:
		return true
	case ContentLimit:
		return true
	case ContentRedacted:
		return true
	case ContentTruncated:
		return true
	case DisplayLimit:
		return true
	case IdentityUnavailable:
		return true
	case ResultUnavailable:
		return true
	case UnsupportedContent:
		return true
	default:
		return false
	}
}

// Defines values for NativeMcpDisplayResultKind.
const (
	Absent      NativeMcpDisplayResultKind = "absent"
	Empty       NativeMcpDisplayResultKind = "empty"
	Null        NativeMcpDisplayResultKind = "null"
	Omitted     NativeMcpDisplayResultKind = "omitted"
	Text        NativeMcpDisplayResultKind = "text"
	Unsupported NativeMcpDisplayResultKind = "unsupported"
)

// Valid indicates whether the value is a known member of the NativeMcpDisplayResultKind enum.
func (e NativeMcpDisplayResultKind) Valid() bool {
	switch e {
	case Absent:
		return true
	case Empty:
		return true
	case Null:
		return true
	case Omitted:
		return true
	case Text:
		return true
	case Unsupported:
		return true
	default:
		return false
	}
}

// Defines values for NativeNotificationAvailability.
const (
	NativeNotificationAvailabilityAvailable   NativeNotificationAvailability = "available"
	NativeNotificationAvailabilityPartial     NativeNotificationAvailability = "partial"
	NativeNotificationAvailabilityUnavailable NativeNotificationAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the NativeNotificationAvailability enum.
func (e NativeNotificationAvailability) Valid() bool {
	switch e {
	case NativeNotificationAvailabilityAvailable:
		return true
	case NativeNotificationAvailabilityPartial:
		return true
	case NativeNotificationAvailabilityUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for NativeNotificationSource.
const (
	ProjectionNotice    NativeNotificationSource = "projection_notice"
	RuntimeNotification NativeNotificationSource = "runtime_notification"
)

// Valid indicates whether the value is a known member of the NativeNotificationSource enum.
func (e NativeNotificationSource) Valid() bool {
	switch e {
	case ProjectionNotice:
		return true
	case RuntimeNotification:
		return true
	default:
		return false
	}
}

// Defines values for NativePlanStepStatus.
const (
	NativePlanStepStatusCompleted  NativePlanStepStatus = "completed"
	NativePlanStepStatusInProgress NativePlanStepStatus = "inProgress"
	NativePlanStepStatusPending    NativePlanStepStatus = "pending"
)

// Valid indicates whether the value is a known member of the NativePlanStepStatus enum.
func (e NativePlanStepStatus) Valid() bool {
	switch e {
	case NativePlanStepStatusCompleted:
		return true
	case NativePlanStepStatusInProgress:
		return true
	case NativePlanStepStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for NativeThreadSnapshotAvailability.
const (
	NativeThreadSnapshotAvailabilityPartial     NativeThreadSnapshotAvailability = "partial"
	NativeThreadSnapshotAvailabilityUnavailable NativeThreadSnapshotAvailability = "unavailable"
)

// Valid indicates whether the value is a known member of the NativeThreadSnapshotAvailability enum.
func (e NativeThreadSnapshotAvailability) Valid() bool {
	switch e {
	case NativeThreadSnapshotAvailabilityPartial:
		return true
	case NativeThreadSnapshotAvailabilityUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for NativeThreadSnapshotSchemaVersion.
const (
	N2 NativeThreadSnapshotSchemaVersion = 2
)

// Valid indicates whether the value is a known member of the NativeThreadSnapshotSchemaVersion enum.
func (e NativeThreadSnapshotSchemaVersion) Valid() bool {
	switch e {
	case N2:
		return true
	default:
		return false
	}
}

// Defines values for NativeThreadSnapshotSource.
const (
	RuntimeRead   NativeThreadSnapshotSource = "runtime_read"
	RuntimeResume NativeThreadSnapshotSource = "runtime_resume"
)

// Valid indicates whether the value is a known member of the NativeThreadSnapshotSource enum.
func (e NativeThreadSnapshotSource) Valid() bool {
	switch e {
	case RuntimeRead:
		return true
	case RuntimeResume:
		return true
	default:
		return false
	}
}

// Defines values for NativeTurnStatus.
const (
	Completed   NativeTurnStatus = "completed"
	Failed      NativeTurnStatus = "failed"
	InProgress  NativeTurnStatus = "inProgress"
	Interrupted NativeTurnStatus = "interrupted"
)

// Valid indicates whether the value is a known member of the NativeTurnStatus enum.
func (e NativeTurnStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case Failed:
		return true
	case InProgress:
		return true
	case Interrupted:
		return true
	default:
		return false
	}
}

// NativeError defines model for NativeError.
type NativeError struct {
	Availability NativeErrorAvailability `json:"availability"`

	// CodexErrorInfo Allowlisted native discriminator. Unknown native details are omitted.
	CodexErrorInfo *NativeErrorCodexErrorInfo `json:"codexErrorInfo,omitempty"`

	// MessageText Bounded redacted native message, not an inferred execution result.
	MessageText *string `json:"messageText,omitempty"`
}

// NativeErrorAvailability defines model for NativeError.Availability.
type NativeErrorAvailability string

// NativeErrorCodexErrorInfo Allowlisted native discriminator. Unknown native details are omitted.
type NativeErrorCodexErrorInfo string

// NativeEvent defines model for NativeEvent.
type NativeEvent struct {
	AgentSessionId openapi_types.UUID   `json:"agent_session_id"`
	CodexThreadId  openapi_types.UUID   `json:"codex_thread_id"`
	EventId        openapi_types.UUID   `json:"event_id"`
	EventType      NativeEventEventType `json:"event_type"`
	ItemId         *string              `json:"item_id,omitempty"`
	OccurredAt     time.Time            `json:"occurred_at"`
	Payload        struct {
		Native NativeNotification `json:"native"`
	} `json:"payload"`
	SchemaVersion NativeEventSchemaVersion `json:"schema_version"`
	Sequence      int64                    `json:"sequence"`
	StreamId      openapi_types.UUID       `json:"stream_id"`
	TaskId        openapi_types.UUID       `json:"task_id"`
	Terminal      bool                     `json:"terminal"`
	TurnId        *string                  `json:"turn_id,omitempty"`
}

// NativeEventEventType defines model for NativeEvent.EventType.
type NativeEventEventType string

// NativeEventSchemaVersion defines model for NativeEvent.SchemaVersion.
type NativeEventSchemaVersion int

// NativeItem defines model for NativeItem.
type NativeItem struct {
	// ArgumentsSummary Metadata display only; raw native arguments never leave Host.
	ArgumentsSummary *string `json:"argumentsSummary,omitempty"`

	// Availability Completeness of this safe display projection, independent of the native execution status.
	Availability NativeItemAvailability `json:"availability"`
	ClientId     *string                `json:"clientId,omitempty"`

	// CommandLabel Security projection label, not the original command. No execution semantics are inferred.
	CommandLabel *string   `json:"commandLabel,omitempty"`
	Content      *[]string `json:"content,omitempty"`

	// CwdLabel Workspace-relative display label; never the native absolute path.
	CwdLabel   *string `json:"cwdLabel,omitempty"`
	DurationMs *int64  `json:"durationMs,omitempty"`
	ExitCode   *int32  `json:"exitCode,omitempty"`
	Id         string  `json:"id"`

	// Mcp Display-only native MCP facts. No raw arguments/error/meta/resources/structuredContent and no business field parsing. Limits do not change execution status. Host bounds total UTF-8 text at 256KiB and first 32 original content entries. Confidentiality may replace entire lines.
	Mcp *NativeMcpDisplay `json:"mcp,omitempty"`

	// OutputText Bounded, redacted projection of native aggregatedOutput. Omitted when native output is null or unavailable.
	OutputText *string          `json:"outputText,omitempty"`
	Phase      *NativeItemPhase `json:"phase,omitempty"`

	// ResultSummary Metadata display only, omitted when native result is absent or null.
	ResultSummary *string           `json:"resultSummary,omitempty"`
	Status        *NativeItemStatus `json:"status,omitempty"`
	Summary       *[]string         `json:"summary,omitempty"`
	Text          *string           `json:"text,omitempty"`

	// ToolLabel Safe display label, not a registered tool identifier. Tool registration is outside FEAT-132.
	ToolLabel *string        `json:"toolLabel,omitempty"`
	Type      NativeItemType `json:"type"`
}

// NativeItemAvailability Completeness of this safe display projection, independent of the native execution status.
type NativeItemAvailability string

// NativeItemPhase defines model for NativeItem.Phase.
type NativeItemPhase string

// NativeItemStatus defines model for NativeItem.Status.
type NativeItemStatus string

// NativeItemType defines model for NativeItem.Type.
type NativeItemType string

// NativeMcpDisplay Display-only native MCP facts. No raw arguments/error/meta/resources/structuredContent and no business field parsing. Limits do not change execution status. Host bounds total UTF-8 text at 256KiB and first 32 original content entries. Confidentiality may replace entire lines.
type NativeMcpDisplay struct {
	Diagnostics []NativeMcpDisplayDiagnostics `json:"diagnostics"`
	ResultKind  NativeMcpDisplayResultKind    `json:"resultKind"`
	Server      *string                       `json:"server,omitempty"`
	Texts       []NativeMcpText               `json:"texts"`
	Tool        *string                       `json:"tool,omitempty"`
}

// NativeMcpDisplayDiagnostics defines model for NativeMcpDisplay.Diagnostics.
type NativeMcpDisplayDiagnostics string

// NativeMcpDisplayResultKind defines model for NativeMcpDisplay.ResultKind.
type NativeMcpDisplayResultKind string

// NativeMcpText defines model for NativeMcpText.
type NativeMcpText struct {
	// Index Original native content array index; never renumber after filtering.
	Index int `json:"index"`

	// Text Complete native text block after existing whole-line confidentiality projection, then UTF-8 truncation. Plain text only; links remain inert.
	Text string `json:"text"`
}

// NativeNotification defines model for NativeNotification.
type NativeNotification struct {
	Availability NativeNotificationAvailability `json:"availability"`
	Code         *string                        `json:"code,omitempty"`
	Delta        *string                        `json:"delta,omitempty"`
	Explanation  *string                        `json:"explanation,omitempty"`
	Index        *int                           `json:"index,omitempty"`
	Item         *NativeItem                    `json:"item,omitempty"`
	ItemId       *string                        `json:"itemId,omitempty"`
	Method       string                         `json:"method"`
	Plan         *[]NativePlanStep              `json:"plan,omitempty"`
	Source       NativeNotificationSource       `json:"source"`
	ThreadId     string                         `json:"threadId"`
	Turn         *NativeTurn                    `json:"turn,omitempty"`
	TurnId       *string                        `json:"turnId,omitempty"`
}

// NativeNotificationAvailability defines model for NativeNotification.Availability.
type NativeNotificationAvailability string

// NativeNotificationSource defines model for NativeNotification.Source.
type NativeNotificationSource string

// NativePlanStep defines model for NativePlanStep.
type NativePlanStep struct {
	Status NativePlanStepStatus `json:"status"`
	Step   string               `json:"step"`
}

// NativePlanStepStatus defines model for NativePlanStep.Status.
type NativePlanStepStatus string

// NativeThreadSnapshot defines model for NativeThreadSnapshot.
type NativeThreadSnapshot struct {
	Availability  NativeThreadSnapshotAvailability  `json:"availability"`
	SchemaVersion NativeThreadSnapshotSchemaVersion `json:"schema_version"`
	Source        NativeThreadSnapshotSource        `json:"source"`
	ThreadId      string                            `json:"thread_id"`
	Turns         []NativeTurn                      `json:"turns"`
}

// NativeThreadSnapshotAvailability defines model for NativeThreadSnapshot.Availability.
type NativeThreadSnapshotAvailability string

// NativeThreadSnapshotSchemaVersion defines model for NativeThreadSnapshot.SchemaVersion.
type NativeThreadSnapshotSchemaVersion int

// NativeThreadSnapshotSource defines model for NativeThreadSnapshot.Source.
type NativeThreadSnapshotSource string

// NativeTurn defines model for NativeTurn.
type NativeTurn struct {
	Error *NativeError `json:"error,omitempty"`

	// ErrorCode Safe diagnostic category for a native error; not the raw error payload. Native status is preserved separately.
	ErrorCode     *string           `json:"errorCode,omitempty"`
	Id            string            `json:"id"`
	Items         []NativeItem      `json:"items"`
	ItemsComplete bool              `json:"itemsComplete"`
	Status        *NativeTurnStatus `json:"status"`
}

// NativeTurnStatus defines model for NativeTurn.Status.
type NativeTurnStatus string

// localBearerContextKey is the context key for LocalBearer security scheme
type localBearerContextKey string

// StreamNativeConversationParams defines parameters for StreamNativeConversation.
type StreamNativeConversationParams struct {
	StreamId    *openapi_types.UUID `form:"stream_id,omitempty" json:"stream_id,omitempty"`
	After       *int64              `form:"after,omitempty" json:"after,omitempty"`
	LastEventID *string             `json:"Last-Event-ID,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ReadNativeThread request
	ReadNativeThread(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StreamNativeConversation request
	StreamNativeConversation(ctx context.Context, agentSessionId openapi_types.UUID, params *StreamNativeConversationParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ReadNativeThread(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadNativeThreadRequest(c.Server, agentSessionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StreamNativeConversation(ctx context.Context, agentSessionId openapi_types.UUID, params *StreamNativeConversationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStreamNativeConversationRequest(c.Server, agentSessionId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewReadNativeThreadRequest generates requests for ReadNativeThread
func NewReadNativeThreadRequest(server string, agentSessionId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "agent_session_id", agentSessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/agent-sessions/%s/native-thread", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStreamNativeConversationRequest generates requests for StreamNativeConversation
func NewStreamNativeConversationRequest(server string, agentSessionId openapi_types.UUID, params *StreamNativeConversationParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "agent_session_id", agentSessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/agent-sessions/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.StreamId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "stream_id", *params.StreamId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.After != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "after", *params.After, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.LastEventID != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Last-Event-ID", *params.LastEventID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Last-Event-ID", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ReadNativeThreadWithResponse request
	ReadNativeThreadWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ReadNativeThreadResponse, error)

	// StreamNativeConversationWithResponse request
	StreamNativeConversationWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, params *StreamNativeConversationParams, reqEditors ...RequestEditorFn) (*StreamNativeConversationResponse, error)
}

type ReadNativeThreadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NativeThreadSnapshot
}

// Status returns HTTPResponse.Status
func (r ReadNativeThreadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadNativeThreadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReadNativeThreadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StreamNativeConversationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r StreamNativeConversationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StreamNativeConversationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StreamNativeConversationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ReadNativeThreadWithResponse request returning *ReadNativeThreadResponse
func (c *ClientWithResponses) ReadNativeThreadWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ReadNativeThreadResponse, error) {
	rsp, err := c.ReadNativeThread(ctx, agentSessionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadNativeThreadResponse(rsp)
}

// StreamNativeConversationWithResponse request returning *StreamNativeConversationResponse
func (c *ClientWithResponses) StreamNativeConversationWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, params *StreamNativeConversationParams, reqEditors ...RequestEditorFn) (*StreamNativeConversationResponse, error) {
	rsp, err := c.StreamNativeConversation(ctx, agentSessionId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStreamNativeConversationResponse(rsp)
}

// ParseReadNativeThreadResponse parses an HTTP response from a ReadNativeThreadWithResponse call
func ParseReadNativeThreadResponse(rsp *http.Response) (*ReadNativeThreadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadNativeThreadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NativeThreadSnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStreamNativeConversationResponse parses an HTTP response from a StreamNativeConversationWithResponse call
func ParseStreamNativeConversationResponse(rsp *http.Response) (*StreamNativeConversationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StreamNativeConversationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
