/* eslint-disable */
// Generated by scripts/generate.mjs. Do not edit by hand.
export const schemas = [
  {
    "path": "jsonschema/agent/event.schema.json",
    "schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://contracts.yijie.ai/agent/event.schema.json",
      "title": "AgentEvent",
      "type": "object",
      "required": [
        "task_id",
        "event_type"
      ],
      "properties": {
        "task_id": {
          "type": "string"
        },
        "codex_thread_id": {
          "type": "string"
        },
        "event_type": {
          "type": "string"
        }
      }
    }
  },
  {
    "path": "jsonschema/chat/message.schema.json",
    "schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://contracts.yijie.ai/chat/message.schema.json",
      "title": "ChatMessage",
      "type": "object",
      "required": [
        "id",
        "role",
        "content"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "role": {
          "type": "string",
          "enum": [
            "user",
            "assistant",
            "tool",
            "system"
          ]
        },
        "content": {
          "type": "string"
        }
      }
    }
  },
  {
    "path": "jsonschema/ecommerce/listing.schema.json",
    "schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://contracts.yijie.ai/ecommerce/listing.schema.json",
      "title": "Listing",
      "type": "object",
      "required": [
        "platform",
        "url"
      ],
      "properties": {
        "platform": {
          "type": "string"
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "title": {
          "type": "string"
        }
      }
    }
  },
  {
    "path": "jsonschema/skills/skill-manifest.schema.json",
    "schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://contracts.yijie.ai/skills/skill-manifest.schema.json",
      "title": "SkillManifest",
      "type": "object",
      "required": [
        "name",
        "version",
        "risk_level"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "risk_level": {
          "type": "string",
          "enum": [
            "low",
            "medium",
            "high"
          ]
        }
      }
    }
  },
  {
    "path": "jsonschema/task/task.schema.json",
    "schema": {
      "$schema": "https://json-schema.org/draft/2020-12/schema",
      "$id": "https://contracts.yijie.ai/task/task.schema.json",
      "title": "AgentTask",
      "type": "object",
      "required": [
        "id",
        "status",
        "title"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "draft",
            "running",
            "waiting_approval",
            "completed",
            "failed"
          ]
        },
        "title": {
          "type": "string"
        }
      }
    }
  }
] as const;

export type YijieSchemaPath = (typeof schemas)[number]['path'];
