// Package scheduledrecovery provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package scheduledrecovery

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	LocalBearerScopes localBearerContextKey = "localBearer.Scopes"
)

// Defines values for MappingState.
const (
	Bound    MappingState = "bound"
	Reserved MappingState = "reserved"
)

// Valid indicates whether the value is a known member of the MappingState enum.
func (e MappingState) Valid() bool {
	switch e {
	case Bound:
		return true
	case Reserved:
		return true
	default:
		return false
	}
}

// Defines values for OperationState.
const (
	Accepted  OperationState = "accepted"
	Pending   OperationState = "pending"
	Uncertain OperationState = "uncertain"
)

// Valid indicates whether the value is a known member of the OperationState enum.
func (e OperationState) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Pending:
		return true
	case Uncertain:
		return true
	default:
		return false
	}
}

// Defines values for RecoveryErrorErrorCode.
const (
	InvalidRequest         RecoveryErrorErrorCode = "invalid_request"
	RecoveryRecordNotFound RecoveryErrorErrorCode = "recovery_record_not_found"
	RecoveryUnavailable    RecoveryErrorErrorCode = "recovery_unavailable"
	Unauthorized           RecoveryErrorErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the RecoveryErrorErrorCode enum.
func (e RecoveryErrorErrorCode) Valid() bool {
	switch e {
	case InvalidRequest:
		return true
	case RecoveryRecordNotFound:
		return true
	case RecoveryUnavailable:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// CanonicalID defines model for CanonicalID.
type CanonicalID = openapi_types.UUID

// MappingState defines model for MappingState.
type MappingState string

// OperationState defines model for OperationState.
type OperationState string

// RecoveryError defines model for RecoveryError.
type RecoveryError struct {
	Error struct {
		Code    RecoveryErrorErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// RecoveryErrorErrorCode defines model for RecoveryError.Error.Code.
type RecoveryErrorErrorCode string

// SessionMapping defines model for SessionMapping.
type SessionMapping struct {
	AgentSessionId           CanonicalID  `json:"agent_session_id"`
	CodexThreadId            *CanonicalID `json:"codex_thread_id,omitempty"`
	MappingState             MappingState `json:"mapping_state"`
	RespondingHostInstanceId *CanonicalID `json:"responding_host_instance_id,omitempty"`
	TaskId                   CanonicalID  `json:"task_id"`
}

// TurnOperationResult defines model for TurnOperationResult.
type TurnOperationResult struct {
	AgentSessionId           CanonicalID    `json:"agent_session_id"`
	OperationId              CanonicalID    `json:"operation_id"`
	RespondingHostInstanceId *CanonicalID   `json:"responding_host_instance_id,omitempty"`
	State                    OperationState `json:"state"`
	TurnId                   *CanonicalID   `json:"turn_id,omitempty"`
}

// localBearerContextKey is the context key for localBearer security scheme
type localBearerContextKey string
