// Package runtimepermissionsv2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package runtimepermissionsv2

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	LocalBearerScopes localBearerContextKey = "LocalBearer.Scopes"
)

// Defines values for McpApprovalScopeMarketplace.
const (
	US McpApprovalScopeMarketplace = "US"
)

// Valid indicates whether the value is a known member of the McpApprovalScopeMarketplace enum.
func (e McpApprovalScopeMarketplace) Valid() bool {
	switch e {
	case US:
		return true
	default:
		return false
	}
}

// Defines values for McpApprovalScopeServer.
const (
	Sorftime McpApprovalScopeServer = "sorftime"
)

// Valid indicates whether the value is a known member of the McpApprovalScopeServer enum.
func (e McpApprovalScopeServer) Valid() bool {
	switch e {
	case Sorftime:
		return true
	default:
		return false
	}
}

// Defines values for McpApprovalScopeTool.
const (
	ProductDetail McpApprovalScopeTool = "product_detail"
)

// Valid indicates whether the value is a known member of the McpApprovalScopeTool enum.
func (e McpApprovalScopeTool) Valid() bool {
	switch e {
	case ProductDetail:
		return true
	default:
		return false
	}
}

// Defines values for PermissionMode.
const (
	Ask  PermissionMode = "ask"
	Auto PermissionMode = "auto"
	Full PermissionMode = "full"
)

// Valid indicates whether the value is a known member of the PermissionMode enum.
func (e PermissionMode) Valid() bool {
	switch e {
	case Ask:
		return true
	case Auto:
		return true
	case Full:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeApprovalKind.
const (
	AutoReview  RuntimeApprovalKind = "auto_review"
	Command     RuntimeApprovalKind = "command"
	FileChange  RuntimeApprovalKind = "file_change"
	Mcp         RuntimeApprovalKind = "mcp"
	Permissions RuntimeApprovalKind = "permissions"
)

// Valid indicates whether the value is a known member of the RuntimeApprovalKind enum.
func (e RuntimeApprovalKind) Valid() bool {
	switch e {
	case AutoReview:
		return true
	case Command:
		return true
	case FileChange:
		return true
	case Mcp:
		return true
	case Permissions:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeApprovalStatus.
const (
	Approved    RuntimeApprovalStatus = "approved"
	Cancelled   RuntimeApprovalStatus = "cancelled"
	Pending     RuntimeApprovalStatus = "pending"
	Rejected    RuntimeApprovalStatus = "rejected"
	Unavailable RuntimeApprovalStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the RuntimeApprovalStatus enum.
func (e RuntimeApprovalStatus) Valid() bool {
	switch e {
	case Approved:
		return true
	case Cancelled:
		return true
	case Pending:
		return true
	case Rejected:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Defines values for RuntimeApprovalDecisionDecision.
const (
	ApproveOnce RuntimeApprovalDecisionDecision = "approve_once"
	Cancel      RuntimeApprovalDecisionDecision = "cancel"
	Reject      RuntimeApprovalDecisionDecision = "reject"
)

// Valid indicates whether the value is a known member of the RuntimeApprovalDecisionDecision enum.
func (e RuntimeApprovalDecisionDecision) Valid() bool {
	switch e {
	case ApproveOnce:
		return true
	case Cancel:
		return true
	case Reject:
		return true
	default:
		return false
	}
}

// McpApprovalScope Validated bounded parameters from the actual native Prompt request; not an authorization or Tool Item binding. Only the configured sorftime/product_detail single US ASIN is supported.
type McpApprovalScope struct {
	Asin        string                      `json:"asin"`
	Marketplace McpApprovalScopeMarketplace `json:"marketplace"`
	Server      McpApprovalScopeServer      `json:"server"`
	Tool        McpApprovalScopeTool        `json:"tool"`
}

// McpApprovalScopeMarketplace defines model for McpApprovalScope.Marketplace.
type McpApprovalScopeMarketplace string

// McpApprovalScopeServer defines model for McpApprovalScope.Server.
type McpApprovalScopeServer string

// McpApprovalScopeTool defines model for McpApprovalScope.Tool.
type McpApprovalScopeTool string

// McpPermissionScopeRequest defines model for McpPermissionScopeRequest.
type McpPermissionScopeRequest struct {
	// Mode ask = on-request/user/workspace-write; auto = on-request/auto_review/workspace-write; full = never/user/danger-full-access. Native OS restrictions still apply.
	Mode PermissionMode `json:"mode"`
}

// McpPermissionScopeResult defines model for McpPermissionScopeResult.
type McpPermissionScopeResult struct {
	// Active Whether the scoped Sorftime configuration remains enabled. Returning to ask does not silently reactivate it.
	Active bool `json:"active"`

	// RuntimeRestarted True only after normal EOF exit, cleanup and source-verified restart without Sorftime.
	RuntimeRestarted bool `json:"runtimeRestarted"`
}

// PermissionMode ask = on-request/user/workspace-write; auto = on-request/auto_review/workspace-write; full = never/user/danger-full-access. Native OS restrictions still apply.
type PermissionMode string

// RuntimeApproval defines model for RuntimeApproval.
type RuntimeApproval struct {
	Id   openapi_types.UUID  `json:"id"`
	Kind RuntimeApprovalKind `json:"kind"`

	// Mcp Validated bounded parameters from the actual native Prompt request; not an authorization or Tool Item binding. Only the configured sorftime/product_detail single US ASIN is supported.
	Mcp *McpApprovalScope `json:"mcp,omitempty"`

	// Reason Redacted Runtime reason or automatic assessment
	Reason string `json:"reason"`

	// Scope Display-only affected command cwd, files or network target
	Scope  string                `json:"scope"`
	Status RuntimeApprovalStatus `json:"status"`

	// Summary Display-only escaped and redacted operation summary
	Summary string `json:"summary"`
}

// RuntimeApprovalKind defines model for RuntimeApproval.Kind.
type RuntimeApprovalKind string

// RuntimeApprovalStatus defines model for RuntimeApproval.Status.
type RuntimeApprovalStatus string

// RuntimeApprovalDecision approve_once/reject retain original FEAT-152 semantics; cancel is allowed only for MCP and maps to native elicitation cancel. Unsupported kinds never gain new choices.
type RuntimeApprovalDecision struct {
	Decision RuntimeApprovalDecisionDecision `json:"decision"`
}

// RuntimeApprovalDecisionDecision defines model for RuntimeApprovalDecision.Decision.
type RuntimeApprovalDecisionDecision string

// RuntimeApprovalSnapshot defines model for RuntimeApprovalSnapshot.
type RuntimeApprovalSnapshot struct {
	Requests []RuntimeApproval `json:"requests"`
}

// localBearerContextKey is the context key for LocalBearer security scheme
type localBearerContextKey string

// DecideRuntimeApprovalJSONRequestBody defines body for DecideRuntimeApproval for application/json ContentType.
type DecideRuntimeApprovalJSONRequestBody = RuntimeApprovalDecision

// PrepareMcpPermissionScopeJSONRequestBody defines body for PrepareMcpPermissionScope for application/json ContentType.
type PrepareMcpPermissionScopeJSONRequestBody = McpPermissionScopeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListRuntimeApprovals request
	ListRuntimeApprovals(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DecideRuntimeApprovalWithBody request with any body
	DecideRuntimeApprovalWithBody(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DecideRuntimeApproval(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, body DecideRuntimeApprovalJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PrepareMcpPermissionScopeWithBody request with any body
	PrepareMcpPermissionScopeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PrepareMcpPermissionScope(ctx context.Context, body PrepareMcpPermissionScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListRuntimeApprovals(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRuntimeApprovalsRequest(c.Server, agentSessionId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DecideRuntimeApprovalWithBody(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDecideRuntimeApprovalRequestWithBody(c.Server, agentSessionId, approvalId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DecideRuntimeApproval(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, body DecideRuntimeApprovalJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDecideRuntimeApprovalRequest(c.Server, agentSessionId, approvalId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PrepareMcpPermissionScopeWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPrepareMcpPermissionScopeRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PrepareMcpPermissionScope(ctx context.Context, body PrepareMcpPermissionScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPrepareMcpPermissionScopeRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListRuntimeApprovalsRequest generates requests for ListRuntimeApprovals
func NewListRuntimeApprovalsRequest(server string, agentSessionId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "agent_session_id", agentSessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/agent-sessions/%s/runtime-approvals", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDecideRuntimeApprovalRequest calls the generic DecideRuntimeApproval builder with application/json body
func NewDecideRuntimeApprovalRequest(server string, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, body DecideRuntimeApprovalJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDecideRuntimeApprovalRequestWithBody(server, agentSessionId, approvalId, "application/json", bodyReader)
}

// NewDecideRuntimeApprovalRequestWithBody generates requests for DecideRuntimeApproval with any type of body
func NewDecideRuntimeApprovalRequestWithBody(server string, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "agent_session_id", agentSessionId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "approval_id", approvalId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/agent-sessions/%s/runtime-approvals/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPrepareMcpPermissionScopeRequest calls the generic PrepareMcpPermissionScope builder with application/json body
func NewPrepareMcpPermissionScopeRequest(server string, body PrepareMcpPermissionScopeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPrepareMcpPermissionScopeRequestWithBody(server, "application/json", bodyReader)
}

// NewPrepareMcpPermissionScopeRequestWithBody generates requests for PrepareMcpPermissionScope with any type of body
func NewPrepareMcpPermissionScopeRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v2/runtime-mcp/permission-scope")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListRuntimeApprovalsWithResponse request
	ListRuntimeApprovalsWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ListRuntimeApprovalsResponse, error)

	// DecideRuntimeApprovalWithBodyWithResponse request with any body
	DecideRuntimeApprovalWithBodyWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DecideRuntimeApprovalResponse, error)

	DecideRuntimeApprovalWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, body DecideRuntimeApprovalJSONRequestBody, reqEditors ...RequestEditorFn) (*DecideRuntimeApprovalResponse, error)

	// PrepareMcpPermissionScopeWithBodyWithResponse request with any body
	PrepareMcpPermissionScopeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PrepareMcpPermissionScopeResponse, error)

	PrepareMcpPermissionScopeWithResponse(ctx context.Context, body PrepareMcpPermissionScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*PrepareMcpPermissionScopeResponse, error)
}

type ListRuntimeApprovalsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeApprovalSnapshot
}

// Status returns HTTPResponse.Status
func (r ListRuntimeApprovalsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListRuntimeApprovalsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListRuntimeApprovalsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DecideRuntimeApprovalResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeApproval
}

// Status returns HTTPResponse.Status
func (r DecideRuntimeApprovalResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DecideRuntimeApprovalResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DecideRuntimeApprovalResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PrepareMcpPermissionScopeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *McpPermissionScopeResult
}

// Status returns HTTPResponse.Status
func (r PrepareMcpPermissionScopeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PrepareMcpPermissionScopeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PrepareMcpPermissionScopeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListRuntimeApprovalsWithResponse request returning *ListRuntimeApprovalsResponse
func (c *ClientWithResponses) ListRuntimeApprovalsWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, reqEditors ...RequestEditorFn) (*ListRuntimeApprovalsResponse, error) {
	rsp, err := c.ListRuntimeApprovals(ctx, agentSessionId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRuntimeApprovalsResponse(rsp)
}

// DecideRuntimeApprovalWithBodyWithResponse request with arbitrary body returning *DecideRuntimeApprovalResponse
func (c *ClientWithResponses) DecideRuntimeApprovalWithBodyWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DecideRuntimeApprovalResponse, error) {
	rsp, err := c.DecideRuntimeApprovalWithBody(ctx, agentSessionId, approvalId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDecideRuntimeApprovalResponse(rsp)
}

func (c *ClientWithResponses) DecideRuntimeApprovalWithResponse(ctx context.Context, agentSessionId openapi_types.UUID, approvalId openapi_types.UUID, body DecideRuntimeApprovalJSONRequestBody, reqEditors ...RequestEditorFn) (*DecideRuntimeApprovalResponse, error) {
	rsp, err := c.DecideRuntimeApproval(ctx, agentSessionId, approvalId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDecideRuntimeApprovalResponse(rsp)
}

// PrepareMcpPermissionScopeWithBodyWithResponse request with arbitrary body returning *PrepareMcpPermissionScopeResponse
func (c *ClientWithResponses) PrepareMcpPermissionScopeWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PrepareMcpPermissionScopeResponse, error) {
	rsp, err := c.PrepareMcpPermissionScopeWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePrepareMcpPermissionScopeResponse(rsp)
}

func (c *ClientWithResponses) PrepareMcpPermissionScopeWithResponse(ctx context.Context, body PrepareMcpPermissionScopeJSONRequestBody, reqEditors ...RequestEditorFn) (*PrepareMcpPermissionScopeResponse, error) {
	rsp, err := c.PrepareMcpPermissionScope(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePrepareMcpPermissionScopeResponse(rsp)
}

// ParseListRuntimeApprovalsResponse parses an HTTP response from a ListRuntimeApprovalsWithResponse call
func ParseListRuntimeApprovalsResponse(rsp *http.Response) (*ListRuntimeApprovalsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRuntimeApprovalsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeApprovalSnapshot
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDecideRuntimeApprovalResponse parses an HTTP response from a DecideRuntimeApprovalWithResponse call
func ParseDecideRuntimeApprovalResponse(rsp *http.Response) (*DecideRuntimeApprovalResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DecideRuntimeApprovalResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeApproval
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePrepareMcpPermissionScopeResponse parses an HTTP response from a PrepareMcpPermissionScopeWithResponse call
func ParsePrepareMcpPermissionScopeResponse(rsp *http.Response) (*PrepareMcpPermissionScopeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PrepareMcpPermissionScopeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest McpPermissionScopeResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
