// Package nativetiming provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package nativetiming

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	LocalBearerScopes localBearerContextKey = "LocalBearer.Scopes"
)

// Defines values for NativeTurnTimingSchemaVersion.
const (
	N1 NativeTurnTimingSchemaVersion = 1
)

// Valid indicates whether the value is a known member of the NativeTurnTimingSchemaVersion enum.
func (e NativeTurnTimingSchemaVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for TimeFieldState.
const (
	Invalid TimeFieldState = "invalid"
	Known   TimeFieldState = "known"
	Unknown TimeFieldState = "unknown"
)

// Valid indicates whether the value is a known member of the TimeFieldState enum.
func (e TimeFieldState) Valid() bool {
	switch e {
	case Invalid:
		return true
	case Known:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for TimingErrorCode.
const (
	InvalidRequest               TimingErrorCode = "invalid_request"
	NativeTimingIdentityMismatch TimingErrorCode = "native_timing_identity_mismatch"
	NativeTimingLimitExceeded    TimingErrorCode = "native_timing_limit_exceeded"
	NativeTimingTimeout          TimingErrorCode = "native_timing_timeout"
	NativeTimingUnavailable      TimingErrorCode = "native_timing_unavailable"
	SessionNotFound              TimingErrorCode = "session_not_found"
	TurnNotFound                 TimingErrorCode = "turn_not_found"
	Unauthorized                 TimingErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the TimingErrorCode enum.
func (e TimingErrorCode) Valid() bool {
	switch e {
	case InvalidRequest:
		return true
	case NativeTimingIdentityMismatch:
		return true
	case NativeTimingLimitExceeded:
		return true
	case NativeTimingTimeout:
		return true
	case NativeTimingUnavailable:
		return true
	case SessionNotFound:
		return true
	case TurnNotFound:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for TimingSource.
const (
	RuntimeRead TimingSource = "runtime_read"
)

// Valid indicates whether the value is a known member of the TimingSource enum.
func (e TimingSource) Valid() bool {
	switch e {
	case RuntimeRead:
		return true
	default:
		return false
	}
}

// CanonicalID Canonical non-zero UUID; identity is checked against the managed mapping.
type CanonicalID = openapi_types.UUID

// DurationMsFact Runtime whole-turn elapsed milliseconds, including its waits. Not item/model-only time and not derived from integer seconds.
type DurationMsFact struct {
	State TimeFieldState `json:"state"`
	Value *int64         `json:"value,omitempty"`
}

// NativeTurnTiming defines model for NativeTurnTiming.
type NativeTurnTiming struct {
	// AgentSessionId Canonical non-zero UUID; identity is checked against the managed mapping.
	AgentSessionId CanonicalID `json:"agent_session_id"`

	// CompletedAt Runtime Unix seconds, not local receipt/schedule time. Omitted/null native field is unknown; malformed or out-of-range is invalid. Zero is valid.
	CompletedAt UnixSecondsFact `json:"completed_at"`

	// DurationMs Runtime whole-turn elapsed milliseconds, including its waits. Not item/model-only time and not derived from integer seconds.
	DurationMs    DurationMsFact                `json:"duration_ms"`
	SchemaVersion NativeTurnTimingSchemaVersion `json:"schema_version"`
	Source        TimingSource                  `json:"source"`

	// StartedAt Runtime Unix seconds, not local receipt/schedule time. Omitted/null native field is unknown; malformed or out-of-range is invalid. Zero is valid.
	StartedAt UnixSecondsFact `json:"started_at"`

	// ThreadId Canonical non-zero UUID; identity is checked against the managed mapping.
	ThreadId CanonicalID `json:"thread_id"`

	// TurnId Canonical non-zero UUID; identity is checked against the managed mapping.
	TurnId CanonicalID `json:"turn_id"`
}

// NativeTurnTimingSchemaVersion defines model for NativeTurnTiming.SchemaVersion.
type NativeTurnTimingSchemaVersion int

// TimeFieldState defines model for TimeFieldState.
type TimeFieldState string

// TimingError defines model for TimingError.
type TimingError struct {
	Error struct {
		Code    TimingErrorCode `json:"code"`
		Message string          `json:"message"`
	} `json:"error"`
}

// TimingErrorCode defines model for TimingErrorCode.
type TimingErrorCode string

// TimingSource defines model for TimingSource.
type TimingSource string

// UnixSecondsFact Runtime Unix seconds, not local receipt/schedule time. Omitted/null native field is unknown; malformed or out-of-range is invalid. Zero is valid.
type UnixSecondsFact struct {
	State TimeFieldState `json:"state"`
	Value *int64         `json:"value,omitempty"`
}

// localBearerContextKey is the context key for LocalBearer security scheme
type localBearerContextKey string
