// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yijie/events/v2/agent_session.proto

package eventsv2

import (
	v1 "github.com/36Dge/yijie-contracts/sdks/go/protobuf/yijie/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEventType int32

const (
	AgentEventType_AGENT_EVENT_TYPE_UNSPECIFIED                   AgentEventType = 0
	AgentEventType_AGENT_EVENT_TYPE_THREAD_STARTED                AgentEventType = 1
	AgentEventType_AGENT_EVENT_TYPE_TURN_STARTED                  AgentEventType = 2
	AgentEventType_AGENT_EVENT_TYPE_ITEM_STARTED                  AgentEventType = 3
	AgentEventType_AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA      AgentEventType = 4
	AgentEventType_AGENT_EVENT_TYPE_ITEM_COMPLETED                AgentEventType = 5
	AgentEventType_AGENT_EVENT_TYPE_TURN_COMPLETED                AgentEventType = 6
	AgentEventType_AGENT_EVENT_TYPE_ERROR                         AgentEventType = 7
	AgentEventType_AGENT_EVENT_TYPE_WARNING                       AgentEventType = 8
	AgentEventType_AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_DELTA     AgentEventType = 9
	AgentEventType_AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_FINALIZED AgentEventType = 10
)

// Enum value maps for AgentEventType.
var (
	AgentEventType_name = map[int32]string{
		0:  "AGENT_EVENT_TYPE_UNSPECIFIED",
		1:  "AGENT_EVENT_TYPE_THREAD_STARTED",
		2:  "AGENT_EVENT_TYPE_TURN_STARTED",
		3:  "AGENT_EVENT_TYPE_ITEM_STARTED",
		4:  "AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA",
		5:  "AGENT_EVENT_TYPE_ITEM_COMPLETED",
		6:  "AGENT_EVENT_TYPE_TURN_COMPLETED",
		7:  "AGENT_EVENT_TYPE_ERROR",
		8:  "AGENT_EVENT_TYPE_WARNING",
		9:  "AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_DELTA",
		10: "AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_FINALIZED",
	}
	AgentEventType_value = map[string]int32{
		"AGENT_EVENT_TYPE_UNSPECIFIED":                   0,
		"AGENT_EVENT_TYPE_THREAD_STARTED":                1,
		"AGENT_EVENT_TYPE_TURN_STARTED":                  2,
		"AGENT_EVENT_TYPE_ITEM_STARTED":                  3,
		"AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA":      4,
		"AGENT_EVENT_TYPE_ITEM_COMPLETED":                5,
		"AGENT_EVENT_TYPE_TURN_COMPLETED":                6,
		"AGENT_EVENT_TYPE_ERROR":                         7,
		"AGENT_EVENT_TYPE_WARNING":                       8,
		"AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_DELTA":     9,
		"AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_FINALIZED": 10,
	}
)

func (x AgentEventType) Enum() *AgentEventType {
	p := new(AgentEventType)
	*p = x
	return p
}

func (x AgentEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v2_agent_session_proto_enumTypes[0].Descriptor()
}

func (AgentEventType) Type() protoreflect.EnumType {
	return &file_yijie_events_v2_agent_session_proto_enumTypes[0]
}

func (x AgentEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEventType.Descriptor instead.
func (AgentEventType) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{0}
}

type AgentTurnStatus int32

const (
	AgentTurnStatus_AGENT_TURN_STATUS_UNSPECIFIED AgentTurnStatus = 0
	AgentTurnStatus_AGENT_TURN_STATUS_IN_PROGRESS AgentTurnStatus = 1
	AgentTurnStatus_AGENT_TURN_STATUS_COMPLETED   AgentTurnStatus = 2
	AgentTurnStatus_AGENT_TURN_STATUS_INTERRUPTED AgentTurnStatus = 3
	AgentTurnStatus_AGENT_TURN_STATUS_FAILED      AgentTurnStatus = 4
)

// Enum value maps for AgentTurnStatus.
var (
	AgentTurnStatus_name = map[int32]string{
		0: "AGENT_TURN_STATUS_UNSPECIFIED",
		1: "AGENT_TURN_STATUS_IN_PROGRESS",
		2: "AGENT_TURN_STATUS_COMPLETED",
		3: "AGENT_TURN_STATUS_INTERRUPTED",
		4: "AGENT_TURN_STATUS_FAILED",
	}
	AgentTurnStatus_value = map[string]int32{
		"AGENT_TURN_STATUS_UNSPECIFIED": 0,
		"AGENT_TURN_STATUS_IN_PROGRESS": 1,
		"AGENT_TURN_STATUS_COMPLETED":   2,
		"AGENT_TURN_STATUS_INTERRUPTED": 3,
		"AGENT_TURN_STATUS_FAILED":      4,
	}
)

func (x AgentTurnStatus) Enum() *AgentTurnStatus {
	p := new(AgentTurnStatus)
	*p = x
	return p
}

func (x AgentTurnStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentTurnStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v2_agent_session_proto_enumTypes[1].Descriptor()
}

func (AgentTurnStatus) Type() protoreflect.EnumType {
	return &file_yijie_events_v2_agent_session_proto_enumTypes[1]
}

func (x AgentTurnStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentTurnStatus.Descriptor instead.
func (AgentTurnStatus) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{1}
}

type ReasoningFinalizationStatus int32

const (
	ReasoningFinalizationStatus_REASONING_FINALIZATION_STATUS_UNSPECIFIED ReasoningFinalizationStatus = 0
	ReasoningFinalizationStatus_REASONING_FINALIZATION_STATUS_COMPLETE    ReasoningFinalizationStatus = 1
	ReasoningFinalizationStatus_REASONING_FINALIZATION_STATUS_INCOMPLETE  ReasoningFinalizationStatus = 2
	ReasoningFinalizationStatus_REASONING_FINALIZATION_STATUS_UNAVAILABLE ReasoningFinalizationStatus = 3
)

// Enum value maps for ReasoningFinalizationStatus.
var (
	ReasoningFinalizationStatus_name = map[int32]string{
		0: "REASONING_FINALIZATION_STATUS_UNSPECIFIED",
		1: "REASONING_FINALIZATION_STATUS_COMPLETE",
		2: "REASONING_FINALIZATION_STATUS_INCOMPLETE",
		3: "REASONING_FINALIZATION_STATUS_UNAVAILABLE",
	}
	ReasoningFinalizationStatus_value = map[string]int32{
		"REASONING_FINALIZATION_STATUS_UNSPECIFIED": 0,
		"REASONING_FINALIZATION_STATUS_COMPLETE":    1,
		"REASONING_FINALIZATION_STATUS_INCOMPLETE":  2,
		"REASONING_FINALIZATION_STATUS_UNAVAILABLE": 3,
	}
)

func (x ReasoningFinalizationStatus) Enum() *ReasoningFinalizationStatus {
	p := new(ReasoningFinalizationStatus)
	*p = x
	return p
}

func (x ReasoningFinalizationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasoningFinalizationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v2_agent_session_proto_enumTypes[2].Descriptor()
}

func (ReasoningFinalizationStatus) Type() protoreflect.EnumType {
	return &file_yijie_events_v2_agent_session_proto_enumTypes[2]
}

func (x ReasoningFinalizationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasoningFinalizationStatus.Descriptor instead.
func (ReasoningFinalizationStatus) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{2}
}

type ReasoningReasonCode int32

const (
	ReasoningReasonCode_REASONING_REASON_CODE_UNSPECIFIED           ReasoningReasonCode = 0
	ReasoningReasonCode_REASONING_REASON_CODE_REASONING_NOT_EMITTED ReasoningReasonCode = 1
	ReasoningReasonCode_REASONING_REASON_CODE_TURN_INTERRUPTED      ReasoningReasonCode = 2
	ReasoningReasonCode_REASONING_REASON_CODE_STREAM_GAP            ReasoningReasonCode = 3
	ReasoningReasonCode_REASONING_REASON_CODE_RUNTIME_ERROR         ReasoningReasonCode = 4
	ReasoningReasonCode_REASONING_REASON_CODE_LIMIT_EXCEEDED        ReasoningReasonCode = 5
	ReasoningReasonCode_REASONING_REASON_CODE_PROTOCOL_ERROR        ReasoningReasonCode = 6
	ReasoningReasonCode_REASONING_REASON_CODE_HOST_SHUTDOWN         ReasoningReasonCode = 7
)

// Enum value maps for ReasoningReasonCode.
var (
	ReasoningReasonCode_name = map[int32]string{
		0: "REASONING_REASON_CODE_UNSPECIFIED",
		1: "REASONING_REASON_CODE_REASONING_NOT_EMITTED",
		2: "REASONING_REASON_CODE_TURN_INTERRUPTED",
		3: "REASONING_REASON_CODE_STREAM_GAP",
		4: "REASONING_REASON_CODE_RUNTIME_ERROR",
		5: "REASONING_REASON_CODE_LIMIT_EXCEEDED",
		6: "REASONING_REASON_CODE_PROTOCOL_ERROR",
		7: "REASONING_REASON_CODE_HOST_SHUTDOWN",
	}
	ReasoningReasonCode_value = map[string]int32{
		"REASONING_REASON_CODE_UNSPECIFIED":           0,
		"REASONING_REASON_CODE_REASONING_NOT_EMITTED": 1,
		"REASONING_REASON_CODE_TURN_INTERRUPTED":      2,
		"REASONING_REASON_CODE_STREAM_GAP":            3,
		"REASONING_REASON_CODE_RUNTIME_ERROR":         4,
		"REASONING_REASON_CODE_LIMIT_EXCEEDED":        5,
		"REASONING_REASON_CODE_PROTOCOL_ERROR":        6,
		"REASONING_REASON_CODE_HOST_SHUTDOWN":         7,
	}
)

func (x ReasoningReasonCode) Enum() *ReasoningReasonCode {
	p := new(ReasoningReasonCode)
	*p = x
	return p
}

func (x ReasoningReasonCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReasoningReasonCode) Descriptor() protoreflect.EnumDescriptor {
	return file_yijie_events_v2_agent_session_proto_enumTypes[3].Descriptor()
}

func (ReasoningReasonCode) Type() protoreflect.EnumType {
	return &file_yijie_events_v2_agent_session_proto_enumTypes[3]
}

func (x ReasoningReasonCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReasoningReasonCode.Descriptor instead.
func (ReasoningReasonCode) EnumDescriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{3}
}

type ThreadStartedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	ModelProvider string                 `protobuf:"bytes,2,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadStartedPayload) Reset() {
	*x = ThreadStartedPayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadStartedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadStartedPayload) ProtoMessage() {}

func (x *ThreadStartedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadStartedPayload.ProtoReflect.Descriptor instead.
func (*ThreadStartedPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{0}
}

func (x *ThreadStartedPayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ThreadStartedPayload) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

type TurnLifecyclePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AgentTurnStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=yijie.events.v2.AgentTurnStatus" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TurnLifecyclePayload) Reset() {
	*x = TurnLifecyclePayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TurnLifecyclePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TurnLifecyclePayload) ProtoMessage() {}

func (x *TurnLifecyclePayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TurnLifecyclePayload.ProtoReflect.Descriptor instead.
func (*TurnLifecyclePayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{1}
}

func (x *TurnLifecyclePayload) GetStatus() AgentTurnStatus {
	if x != nil {
		return x.Status
	}
	return AgentTurnStatus_AGENT_TURN_STATUS_UNSPECIFIED
}

func (x *TurnLifecyclePayload) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TurnLifecyclePayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ItemLifecyclePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemType      string                 `protobuf:"bytes,1,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemLifecyclePayload) Reset() {
	*x = ItemLifecyclePayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemLifecyclePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemLifecyclePayload) ProtoMessage() {}

func (x *ItemLifecyclePayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemLifecyclePayload.ProtoReflect.Descriptor instead.
func (*ItemLifecyclePayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{2}
}

func (x *ItemLifecyclePayload) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

func (x *ItemLifecyclePayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type AgentMessageDeltaPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         string                 `protobuf:"bytes,1,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessageDeltaPayload) Reset() {
	*x = AgentMessageDeltaPayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessageDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessageDeltaPayload) ProtoMessage() {}

func (x *AgentMessageDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessageDeltaPayload.ProtoReflect.Descriptor instead.
func (*AgentMessageDeltaPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMessageDeltaPayload) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type ReasoningTextDeltaPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zero-based Runtime content part index. Contract range: 0..7.
	ContentIndex uint32 `protobuf:"varint,1,opt,name=content_index,json=contentIndex,proto3" json:"content_index,omitempty"`
	// Non-empty untrusted plain text. Contract maximum: 16 KiB UTF-8.
	Delta         string `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningTextDeltaPayload) Reset() {
	*x = ReasoningTextDeltaPayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningTextDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningTextDeltaPayload) ProtoMessage() {}

func (x *ReasoningTextDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningTextDeltaPayload.ProtoReflect.Descriptor instead.
func (*ReasoningTextDeltaPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{4}
}

func (x *ReasoningTextDeltaPayload) GetContentIndex() uint32 {
	if x != nil {
		return x.ContentIndex
	}
	return 0
}

func (x *ReasoningTextDeltaPayload) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type ReasoningContentPart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parts are unique, zero-based, contiguous, and ascending. Contract range: 0..7.
	ContentIndex uint32 `protobuf:"varint,1,opt,name=content_index,json=contentIndex,proto3" json:"content_index,omitempty"`
	// Non-empty untrusted plain text. Contract maximum: 64 KiB UTF-8.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningContentPart) Reset() {
	*x = ReasoningContentPart{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningContentPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningContentPart) ProtoMessage() {}

func (x *ReasoningContentPart) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningContentPart.ProtoReflect.Descriptor instead.
func (*ReasoningContentPart) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{5}
}

func (x *ReasoningContentPart) GetContentIndex() uint32 {
	if x != nil {
		return x.ContentIndex
	}
	return 0
}

func (x *ReasoningContentPart) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ReasoningTextFinalizedPayload struct {
	state  protoimpl.MessageState      `protogen:"open.v1"`
	Status ReasoningFinalizationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=yijie.events.v2.ReasoningFinalizationStatus" json:"status,omitempty"`
	// Authoritative Runtime completed snapshot. At most eight parts and 128 KiB UTF-8 total.
	Contents []*ReasoningContentPart `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	// Absent for complete; required for incomplete and unavailable.
	ReasonCode    *ReasoningReasonCode `protobuf:"varint,3,opt,name=reason_code,json=reasonCode,proto3,enum=yijie.events.v2.ReasoningReasonCode,oneof" json:"reason_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningTextFinalizedPayload) Reset() {
	*x = ReasoningTextFinalizedPayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningTextFinalizedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningTextFinalizedPayload) ProtoMessage() {}

func (x *ReasoningTextFinalizedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningTextFinalizedPayload.ProtoReflect.Descriptor instead.
func (*ReasoningTextFinalizedPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{6}
}

func (x *ReasoningTextFinalizedPayload) GetStatus() ReasoningFinalizationStatus {
	if x != nil {
		return x.Status
	}
	return ReasoningFinalizationStatus_REASONING_FINALIZATION_STATUS_UNSPECIFIED
}

func (x *ReasoningTextFinalizedPayload) GetContents() []*ReasoningContentPart {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *ReasoningTextFinalizedPayload) GetReasonCode() ReasoningReasonCode {
	if x != nil && x.ReasonCode != nil {
		return *x.ReasonCode
	}
	return ReasoningReasonCode_REASONING_REASON_CODE_UNSPECIFIED
}

type AgentProblemPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WillRetry     bool                   `protobuf:"varint,3,opt,name=will_retry,json=willRetry,proto3" json:"will_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProblemPayload) Reset() {
	*x = AgentProblemPayload{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProblemPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProblemPayload) ProtoMessage() {}

func (x *AgentProblemPayload) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProblemPayload.ProtoReflect.Descriptor instead.
func (*AgentProblemPayload) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{7}
}

func (x *AgentProblemPayload) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AgentProblemPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AgentProblemPayload) GetWillRetry() bool {
	if x != nil {
		return x.WillRetry
	}
	return false
}

type AgentSessionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always 2. Consumers negotiate v2 before the Host emits this message.
	SchemaVersion  uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	EventId        string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	StreamId       string                 `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OccurredAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Trace          *v1.TraceContext       `protobuf:"bytes,6,opt,name=trace,proto3" json:"trace,omitempty"`
	TaskId         string                 `protobuf:"bytes,7,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentSessionId string                 `protobuf:"bytes,8,opt,name=agent_session_id,json=agentSessionId,proto3" json:"agent_session_id,omitempty"`
	CodexThreadId  string                 `protobuf:"bytes,9,opt,name=codex_thread_id,json=codexThreadId,proto3" json:"codex_thread_id,omitempty"`
	TurnId         string                 `protobuf:"bytes,10,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`
	ItemId         string                 `protobuf:"bytes,11,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EventType      AgentEventType         `protobuf:"varint,12,opt,name=event_type,json=eventType,proto3,enum=yijie.events.v2.AgentEventType" json:"event_type,omitempty"`
	// True only for turn_completed. Reasoning finalized is not turn terminal.
	Terminal bool `protobuf:"varint,13,opt,name=terminal,proto3" json:"terminal,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentSessionEvent_ThreadStarted
	//	*AgentSessionEvent_TurnStarted
	//	*AgentSessionEvent_ItemStarted
	//	*AgentSessionEvent_AgentMessageDelta
	//	*AgentSessionEvent_ItemCompleted
	//	*AgentSessionEvent_TurnCompleted
	//	*AgentSessionEvent_Error
	//	*AgentSessionEvent_Warning
	//	*AgentSessionEvent_ReasoningTextDelta
	//	*AgentSessionEvent_ReasoningTextFinalized
	Payload       isAgentSessionEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSessionEvent) Reset() {
	*x = AgentSessionEvent{}
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSessionEvent) ProtoMessage() {}

func (x *AgentSessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_yijie_events_v2_agent_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSessionEvent.ProtoReflect.Descriptor instead.
func (*AgentSessionEvent) Descriptor() ([]byte, []int) {
	return file_yijie_events_v2_agent_session_proto_rawDescGZIP(), []int{8}
}

func (x *AgentSessionEvent) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AgentSessionEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AgentSessionEvent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AgentSessionEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AgentSessionEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *AgentSessionEvent) GetTrace() *v1.TraceContext {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *AgentSessionEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentSessionEvent) GetAgentSessionId() string {
	if x != nil {
		return x.AgentSessionId
	}
	return ""
}

func (x *AgentSessionEvent) GetCodexThreadId() string {
	if x != nil {
		return x.CodexThreadId
	}
	return ""
}

func (x *AgentSessionEvent) GetTurnId() string {
	if x != nil {
		return x.TurnId
	}
	return ""
}

func (x *AgentSessionEvent) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AgentSessionEvent) GetEventType() AgentEventType {
	if x != nil {
		return x.EventType
	}
	return AgentEventType_AGENT_EVENT_TYPE_UNSPECIFIED
}

func (x *AgentSessionEvent) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

func (x *AgentSessionEvent) GetPayload() isAgentSessionEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentSessionEvent) GetThreadStarted() *ThreadStartedPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ThreadStarted); ok {
			return x.ThreadStarted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetTurnStarted() *TurnLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_TurnStarted); ok {
			return x.TurnStarted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetItemStarted() *ItemLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ItemStarted); ok {
			return x.ItemStarted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetAgentMessageDelta() *AgentMessageDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_AgentMessageDelta); ok {
			return x.AgentMessageDelta
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetItemCompleted() *ItemLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ItemCompleted); ok {
			return x.ItemCompleted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetTurnCompleted() *TurnLifecyclePayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_TurnCompleted); ok {
			return x.TurnCompleted
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetError() *AgentProblemPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetWarning() *AgentProblemPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_Warning); ok {
			return x.Warning
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetReasoningTextDelta() *ReasoningTextDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ReasoningTextDelta); ok {
			return x.ReasoningTextDelta
		}
	}
	return nil
}

func (x *AgentSessionEvent) GetReasoningTextFinalized() *ReasoningTextFinalizedPayload {
	if x != nil {
		if x, ok := x.Payload.(*AgentSessionEvent_ReasoningTextFinalized); ok {
			return x.ReasoningTextFinalized
		}
	}
	return nil
}

type isAgentSessionEvent_Payload interface {
	isAgentSessionEvent_Payload()
}

type AgentSessionEvent_ThreadStarted struct {
	ThreadStarted *ThreadStartedPayload `protobuf:"bytes,20,opt,name=thread_started,json=threadStarted,proto3,oneof"`
}

type AgentSessionEvent_TurnStarted struct {
	TurnStarted *TurnLifecyclePayload `protobuf:"bytes,21,opt,name=turn_started,json=turnStarted,proto3,oneof"`
}

type AgentSessionEvent_ItemStarted struct {
	ItemStarted *ItemLifecyclePayload `protobuf:"bytes,22,opt,name=item_started,json=itemStarted,proto3,oneof"`
}

type AgentSessionEvent_AgentMessageDelta struct {
	AgentMessageDelta *AgentMessageDeltaPayload `protobuf:"bytes,23,opt,name=agent_message_delta,json=agentMessageDelta,proto3,oneof"`
}

type AgentSessionEvent_ItemCompleted struct {
	ItemCompleted *ItemLifecyclePayload `protobuf:"bytes,24,opt,name=item_completed,json=itemCompleted,proto3,oneof"`
}

type AgentSessionEvent_TurnCompleted struct {
	TurnCompleted *TurnLifecyclePayload `protobuf:"bytes,25,opt,name=turn_completed,json=turnCompleted,proto3,oneof"`
}

type AgentSessionEvent_Error struct {
	Error *AgentProblemPayload `protobuf:"bytes,26,opt,name=error,proto3,oneof"`
}

type AgentSessionEvent_Warning struct {
	Warning *AgentProblemPayload `protobuf:"bytes,27,opt,name=warning,proto3,oneof"`
}

type AgentSessionEvent_ReasoningTextDelta struct {
	ReasoningTextDelta *ReasoningTextDeltaPayload `protobuf:"bytes,28,opt,name=reasoning_text_delta,json=reasoningTextDelta,proto3,oneof"`
}

type AgentSessionEvent_ReasoningTextFinalized struct {
	ReasoningTextFinalized *ReasoningTextFinalizedPayload `protobuf:"bytes,29,opt,name=reasoning_text_finalized,json=reasoningTextFinalized,proto3,oneof"`
}

func (*AgentSessionEvent_ThreadStarted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_TurnStarted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_ItemStarted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_AgentMessageDelta) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_ItemCompleted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_TurnCompleted) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_Error) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_Warning) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_ReasoningTextDelta) isAgentSessionEvent_Payload() {}

func (*AgentSessionEvent_ReasoningTextFinalized) isAgentSessionEvent_Payload() {}

var File_yijie_events_v2_agent_session_proto protoreflect.FileDescriptor

const file_yijie_events_v2_agent_session_proto_rawDesc = "" +
	"\n" +
	"#yijie/events/v2/agent_session.proto\x12\x0fyijie.events.v2\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cyijie/common/v1/common.proto\"S\n" +
	"\x14ThreadStartedPayload\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12%\n" +
	"\x0emodel_provider\x18\x02 \x01(\tR\rmodelProvider\"\x94\x01\n" +
	"\x14TurnLifecyclePayload\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .yijie.events.v2.AgentTurnStatusR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"G\n" +
	"\x14ItemLifecyclePayload\x12\x1b\n" +
	"\titem_type\x18\x01 \x01(\tR\bitemType\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"0\n" +
	"\x18AgentMessageDeltaPayload\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\tR\x05delta\"V\n" +
	"\x19ReasoningTextDeltaPayload\x12#\n" +
	"\rcontent_index\x18\x01 \x01(\rR\fcontentIndex\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"O\n" +
	"\x14ReasoningContentPart\x12#\n" +
	"\rcontent_index\x18\x01 \x01(\rR\fcontentIndex\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x84\x02\n" +
	"\x1dReasoningTextFinalizedPayload\x12D\n" +
	"\x06status\x18\x01 \x01(\x0e2,.yijie.events.v2.ReasoningFinalizationStatusR\x06status\x12A\n" +
	"\bcontents\x18\x02 \x03(\v2%.yijie.events.v2.ReasoningContentPartR\bcontents\x12J\n" +
	"\vreason_code\x18\x03 \x01(\x0e2$.yijie.events.v2.ReasoningReasonCodeH\x00R\n" +
	"reasonCode\x88\x01\x01B\x0e\n" +
	"\f_reason_code\"b\n" +
	"\x13AgentProblemPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"will_retry\x18\x03 \x01(\bR\twillRetry\"\xb5\n" +
	"\n" +
	"\x11AgentSessionEvent\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x123\n" +
	"\x05trace\x18\x06 \x01(\v2\x1d.yijie.common.v1.TraceContextR\x05trace\x12\x17\n" +
	"\atask_id\x18\a \x01(\tR\x06taskId\x12(\n" +
	"\x10agent_session_id\x18\b \x01(\tR\x0eagentSessionId\x12&\n" +
	"\x0fcodex_thread_id\x18\t \x01(\tR\rcodexThreadId\x12\x17\n" +
	"\aturn_id\x18\n" +
	" \x01(\tR\x06turnId\x12\x17\n" +
	"\aitem_id\x18\v \x01(\tR\x06itemId\x12>\n" +
	"\n" +
	"event_type\x18\f \x01(\x0e2\x1f.yijie.events.v2.AgentEventTypeR\teventType\x12\x1a\n" +
	"\bterminal\x18\r \x01(\bR\bterminal\x12N\n" +
	"\x0ethread_started\x18\x14 \x01(\v2%.yijie.events.v2.ThreadStartedPayloadH\x00R\rthreadStarted\x12J\n" +
	"\fturn_started\x18\x15 \x01(\v2%.yijie.events.v2.TurnLifecyclePayloadH\x00R\vturnStarted\x12J\n" +
	"\fitem_started\x18\x16 \x01(\v2%.yijie.events.v2.ItemLifecyclePayloadH\x00R\vitemStarted\x12[\n" +
	"\x13agent_message_delta\x18\x17 \x01(\v2).yijie.events.v2.AgentMessageDeltaPayloadH\x00R\x11agentMessageDelta\x12N\n" +
	"\x0eitem_completed\x18\x18 \x01(\v2%.yijie.events.v2.ItemLifecyclePayloadH\x00R\ritemCompleted\x12N\n" +
	"\x0eturn_completed\x18\x19 \x01(\v2%.yijie.events.v2.TurnLifecyclePayloadH\x00R\rturnCompleted\x12<\n" +
	"\x05error\x18\x1a \x01(\v2$.yijie.events.v2.AgentProblemPayloadH\x00R\x05error\x12@\n" +
	"\awarning\x18\x1b \x01(\v2$.yijie.events.v2.AgentProblemPayloadH\x00R\awarning\x12^\n" +
	"\x14reasoning_text_delta\x18\x1c \x01(\v2*.yijie.events.v2.ReasoningTextDeltaPayloadH\x00R\x12reasoningTextDelta\x12j\n" +
	"\x18reasoning_text_finalized\x18\x1d \x01(\v2..yijie.events.v2.ReasoningTextFinalizedPayloadH\x00R\x16reasoningTextFinalizedB\t\n" +
	"\apayload*\xb4\x03\n" +
	"\x0eAgentEventType\x12 \n" +
	"\x1cAGENT_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fAGENT_EVENT_TYPE_THREAD_STARTED\x10\x01\x12!\n" +
	"\x1dAGENT_EVENT_TYPE_TURN_STARTED\x10\x02\x12!\n" +
	"\x1dAGENT_EVENT_TYPE_ITEM_STARTED\x10\x03\x12-\n" +
	")AGENT_EVENT_TYPE_ITEM_AGENT_MESSAGE_DELTA\x10\x04\x12#\n" +
	"\x1fAGENT_EVENT_TYPE_ITEM_COMPLETED\x10\x05\x12#\n" +
	"\x1fAGENT_EVENT_TYPE_TURN_COMPLETED\x10\x06\x12\x1a\n" +
	"\x16AGENT_EVENT_TYPE_ERROR\x10\a\x12\x1c\n" +
	"\x18AGENT_EVENT_TYPE_WARNING\x10\b\x12.\n" +
	"*AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_DELTA\x10\t\x122\n" +
	".AGENT_EVENT_TYPE_ITEM_REASONING_TEXT_FINALIZED\x10\n" +
	"*\xb9\x01\n" +
	"\x0fAgentTurnStatus\x12!\n" +
	"\x1dAGENT_TURN_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGENT_TURN_STATUS_IN_PROGRESS\x10\x01\x12\x1f\n" +
	"\x1bAGENT_TURN_STATUS_COMPLETED\x10\x02\x12!\n" +
	"\x1dAGENT_TURN_STATUS_INTERRUPTED\x10\x03\x12\x1c\n" +
	"\x18AGENT_TURN_STATUS_FAILED\x10\x04*\xd5\x01\n" +
	"\x1bReasoningFinalizationStatus\x12-\n" +
	")REASONING_FINALIZATION_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&REASONING_FINALIZATION_STATUS_COMPLETE\x10\x01\x12,\n" +
	"(REASONING_FINALIZATION_STATUS_INCOMPLETE\x10\x02\x12-\n" +
	")REASONING_FINALIZATION_STATUS_UNAVAILABLE\x10\x03*\xe5\x02\n" +
	"\x13ReasoningReasonCode\x12%\n" +
	"!REASONING_REASON_CODE_UNSPECIFIED\x10\x00\x12/\n" +
	"+REASONING_REASON_CODE_REASONING_NOT_EMITTED\x10\x01\x12*\n" +
	"&REASONING_REASON_CODE_TURN_INTERRUPTED\x10\x02\x12$\n" +
	" REASONING_REASON_CODE_STREAM_GAP\x10\x03\x12'\n" +
	"#REASONING_REASON_CODE_RUNTIME_ERROR\x10\x04\x12(\n" +
	"$REASONING_REASON_CODE_LIMIT_EXCEEDED\x10\x05\x12(\n" +
	"$REASONING_REASON_CODE_PROTOCOL_ERROR\x10\x06\x12'\n" +
	"#REASONING_REASON_CODE_HOST_SHUTDOWN\x10\aBLZJgithub.com/36Dge/yijie-contracts/sdks/go/protobuf/yijie/events/v2;eventsv2b\x06proto3"

var (
	file_yijie_events_v2_agent_session_proto_rawDescOnce sync.Once
	file_yijie_events_v2_agent_session_proto_rawDescData []byte
)

func file_yijie_events_v2_agent_session_proto_rawDescGZIP() []byte {
	file_yijie_events_v2_agent_session_proto_rawDescOnce.Do(func() {
		file_yijie_events_v2_agent_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yijie_events_v2_agent_session_proto_rawDesc), len(file_yijie_events_v2_agent_session_proto_rawDesc)))
	})
	return file_yijie_events_v2_agent_session_proto_rawDescData
}

var file_yijie_events_v2_agent_session_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_yijie_events_v2_agent_session_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_yijie_events_v2_agent_session_proto_goTypes = []any{
	(AgentEventType)(0),                   // 0: yijie.events.v2.AgentEventType
	(AgentTurnStatus)(0),                  // 1: yijie.events.v2.AgentTurnStatus
	(ReasoningFinalizationStatus)(0),      // 2: yijie.events.v2.ReasoningFinalizationStatus
	(ReasoningReasonCode)(0),              // 3: yijie.events.v2.ReasoningReasonCode
	(*ThreadStartedPayload)(nil),          // 4: yijie.events.v2.ThreadStartedPayload
	(*TurnLifecyclePayload)(nil),          // 5: yijie.events.v2.TurnLifecyclePayload
	(*ItemLifecyclePayload)(nil),          // 6: yijie.events.v2.ItemLifecyclePayload
	(*AgentMessageDeltaPayload)(nil),      // 7: yijie.events.v2.AgentMessageDeltaPayload
	(*ReasoningTextDeltaPayload)(nil),     // 8: yijie.events.v2.ReasoningTextDeltaPayload
	(*ReasoningContentPart)(nil),          // 9: yijie.events.v2.ReasoningContentPart
	(*ReasoningTextFinalizedPayload)(nil), // 10: yijie.events.v2.ReasoningTextFinalizedPayload
	(*AgentProblemPayload)(nil),           // 11: yijie.events.v2.AgentProblemPayload
	(*AgentSessionEvent)(nil),             // 12: yijie.events.v2.AgentSessionEvent
	(*timestamppb.Timestamp)(nil),         // 13: google.protobuf.Timestamp
	(*v1.TraceContext)(nil),               // 14: yijie.common.v1.TraceContext
}
var file_yijie_events_v2_agent_session_proto_depIdxs = []int32{
	1,  // 0: yijie.events.v2.TurnLifecyclePayload.status:type_name -> yijie.events.v2.AgentTurnStatus
	2,  // 1: yijie.events.v2.ReasoningTextFinalizedPayload.status:type_name -> yijie.events.v2.ReasoningFinalizationStatus
	9,  // 2: yijie.events.v2.ReasoningTextFinalizedPayload.contents:type_name -> yijie.events.v2.ReasoningContentPart
	3,  // 3: yijie.events.v2.ReasoningTextFinalizedPayload.reason_code:type_name -> yijie.events.v2.ReasoningReasonCode
	13, // 4: yijie.events.v2.AgentSessionEvent.occurred_at:type_name -> google.protobuf.Timestamp
	14, // 5: yijie.events.v2.AgentSessionEvent.trace:type_name -> yijie.common.v1.TraceContext
	0,  // 6: yijie.events.v2.AgentSessionEvent.event_type:type_name -> yijie.events.v2.AgentEventType
	4,  // 7: yijie.events.v2.AgentSessionEvent.thread_started:type_name -> yijie.events.v2.ThreadStartedPayload
	5,  // 8: yijie.events.v2.AgentSessionEvent.turn_started:type_name -> yijie.events.v2.TurnLifecyclePayload
	6,  // 9: yijie.events.v2.AgentSessionEvent.item_started:type_name -> yijie.events.v2.ItemLifecyclePayload
	7,  // 10: yijie.events.v2.AgentSessionEvent.agent_message_delta:type_name -> yijie.events.v2.AgentMessageDeltaPayload
	6,  // 11: yijie.events.v2.AgentSessionEvent.item_completed:type_name -> yijie.events.v2.ItemLifecyclePayload
	5,  // 12: yijie.events.v2.AgentSessionEvent.turn_completed:type_name -> yijie.events.v2.TurnLifecyclePayload
	11, // 13: yijie.events.v2.AgentSessionEvent.error:type_name -> yijie.events.v2.AgentProblemPayload
	11, // 14: yijie.events.v2.AgentSessionEvent.warning:type_name -> yijie.events.v2.AgentProblemPayload
	8,  // 15: yijie.events.v2.AgentSessionEvent.reasoning_text_delta:type_name -> yijie.events.v2.ReasoningTextDeltaPayload
	10, // 16: yijie.events.v2.AgentSessionEvent.reasoning_text_finalized:type_name -> yijie.events.v2.ReasoningTextFinalizedPayload
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_yijie_events_v2_agent_session_proto_init() }
func file_yijie_events_v2_agent_session_proto_init() {
	if File_yijie_events_v2_agent_session_proto != nil {
		return
	}
	file_yijie_events_v2_agent_session_proto_msgTypes[6].OneofWrappers = []any{}
	file_yijie_events_v2_agent_session_proto_msgTypes[8].OneofWrappers = []any{
		(*AgentSessionEvent_ThreadStarted)(nil),
		(*AgentSessionEvent_TurnStarted)(nil),
		(*AgentSessionEvent_ItemStarted)(nil),
		(*AgentSessionEvent_AgentMessageDelta)(nil),
		(*AgentSessionEvent_ItemCompleted)(nil),
		(*AgentSessionEvent_TurnCompleted)(nil),
		(*AgentSessionEvent_Error)(nil),
		(*AgentSessionEvent_Warning)(nil),
		(*AgentSessionEvent_ReasoningTextDelta)(nil),
		(*AgentSessionEvent_ReasoningTextFinalized)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yijie_events_v2_agent_session_proto_rawDesc), len(file_yijie_events_v2_agent_session_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yijie_events_v2_agent_session_proto_goTypes,
		DependencyIndexes: file_yijie_events_v2_agent_session_proto_depIdxs,
		EnumInfos:         file_yijie_events_v2_agent_session_proto_enumTypes,
		MessageInfos:      file_yijie_events_v2_agent_session_proto_msgTypes,
	}.Build()
	File_yijie_events_v2_agent_session_proto = out.File
	file_yijie_events_v2_agent_session_proto_goTypes = nil
	file_yijie_events_v2_agent_session_proto_depIdxs = nil
}
