// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yijie/services/agent_host/v1/agent_host.proto

package agenthostv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_yijie_services_agent_host_v1_agent_host_proto protoreflect.FileDescriptor

const file_yijie_services_agent_host_v1_agent_host_proto_rawDesc = "" +
	"\n" +
	"-yijie/services/agent_host/v1/agent_host.proto\x12\x1cyijie.services.agent_host.v12\x12\n" +
	"\x10AgentHostServiceB\\ZZgithub.com/36Dge/yijie-contracts/sdks/go/protobuf/yijie/services/agent_host/v1;agenthostv1b\x06proto3"

var file_yijie_services_agent_host_v1_agent_host_proto_goTypes = []any{}
var file_yijie_services_agent_host_v1_agent_host_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yijie_services_agent_host_v1_agent_host_proto_init() }
func file_yijie_services_agent_host_v1_agent_host_proto_init() {
	if File_yijie_services_agent_host_v1_agent_host_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yijie_services_agent_host_v1_agent_host_proto_rawDesc), len(file_yijie_services_agent_host_v1_agent_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yijie_services_agent_host_v1_agent_host_proto_goTypes,
		DependencyIndexes: file_yijie_services_agent_host_v1_agent_host_proto_depIdxs,
	}.Build()
	File_yijie_services_agent_host_v1_agent_host_proto = out.File
	file_yijie_services_agent_host_v1_agent_host_proto_goTypes = nil
	file_yijie_services_agent_host_v1_agent_host_proto_depIdxs = nil
}
