import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const schemaRoot = path.join(root, "jsonschema");
const tsOut = path.join(root, "sdks/typescript/src/generated.ts");
const goOut = path.join(root, "sdks/go/yijie/generated.go");

async function collectJsonSchemas(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const schemas = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      schemas.push(...(await collectJsonSchemas(fullPath)));
    } else if (entry.name.endsWith(".json")) {
      const relativePath = path.relative(root, fullPath);
      const content = JSON.parse(await readFile(fullPath, "utf8"));
      schemas.push({ path: relativePath, schema: content });
    }
  }

  return schemas;
}

const schemas = await collectJsonSchemas(schemaRoot);

await mkdir(path.dirname(tsOut), { recursive: true });
await writeFile(
  tsOut,
  [
    "/* eslint-disable */",
    "// Generated by scripts/generate.mjs. Do not edit by hand.",
    `export const schemas = ${JSON.stringify(schemas, null, 2)} as const;`,
    "",
    "export type YijieSchemaPath = (typeof schemas)[number]['path'];",
    "",
  ].join("\n"),
);

await mkdir(path.dirname(goOut), { recursive: true });
await writeFile(
  goOut,
  [
    "package yijie",
    "",
    "// Generated by scripts/generate.mjs. Do not edit by hand.",
    `const SchemaCount = ${schemas.length}`,
    "",
  ].join("\n"),
);

console.log(`Generated ${schemas.length} schema entries.`);
