// Package workflowlocal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package workflowlocal

const (
	ServiceBearerScopes serviceBearerContextKey = "ServiceBearer.Scopes"
)

// Defines values for BootstrapNodeTypes.
const (
	BootstrapNodeTypesN1  BootstrapNodeTypes = 1
	BootstrapNodeTypesN15 BootstrapNodeTypes = 15
	BootstrapNodeTypesN2  BootstrapNodeTypes = 2
)

// Valid indicates whether the value is a known member of the BootstrapNodeTypes enum.
func (e BootstrapNodeTypes) Valid() bool {
	switch e {
	case BootstrapNodeTypesN1:
		return true
	case BootstrapNodeTypesN15:
		return true
	case BootstrapNodeTypesN2:
		return true
	default:
		return false
	}
}

// Defines values for EditorExchangeInputProtocolVersion.
const (
	EditorExchangeInputProtocolVersionN1 EditorExchangeInputProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the EditorExchangeInputProtocolVersion enum.
func (e EditorExchangeInputProtocolVersion) Valid() bool {
	switch e {
	case EditorExchangeInputProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for EditorOpenedViewProtocolVersion.
const (
	EditorOpenedViewProtocolVersionN1 EditorOpenedViewProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the EditorOpenedViewProtocolVersion enum.
func (e EditorOpenedViewProtocolVersion) Valid() bool {
	switch e {
	case EditorOpenedViewProtocolVersionN1:
		return true
	default:
		return false
	}
}

// Defines values for EditorOperation.
const (
	EditorOperationBootstrap       EditorOperation = "bootstrap"
	EditorOperationPublishInternal EditorOperation = "publish_internal"
	EditorOperationReadDraft       EditorOperation = "read_draft"
	EditorOperationReadOperation   EditorOperation = "read_operation"
	EditorOperationReadRun         EditorOperation = "read_run"
	EditorOperationSaveDraft       EditorOperation = "save_draft"
	EditorOperationTestDraft       EditorOperation = "test_draft"
)

// Valid indicates whether the value is a known member of the EditorOperation enum.
func (e EditorOperation) Valid() bool {
	switch e {
	case EditorOperationBootstrap:
		return true
	case EditorOperationPublishInternal:
		return true
	case EditorOperationReadDraft:
		return true
	case EditorOperationReadOperation:
		return true
	case EditorOperationReadRun:
		return true
	case EditorOperationSaveDraft:
		return true
	case EditorOperationTestDraft:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	InputTooLarge      ErrorCode = "input_too_large"
	InternalError      ErrorCode = "internal_error"
	InvalidDraft       ErrorCode = "invalid_draft"
	InvalidRequest     ErrorCode = "invalid_request"
	OperationConflict  ErrorCode = "operation_conflict"
	OperationUnknown   ErrorCode = "operation_unknown"
	ProfileDisabled    ErrorCode = "profile_disabled"
	ProtocolMismatch   ErrorCode = "protocol_mismatch"
	ResourceNotFound   ErrorCode = "resource_not_found"
	RevisionConflict   ErrorCode = "revision_conflict"
	RunBusy            ErrorCode = "run_busy"
	ServiceUnavailable ErrorCode = "service_unavailable"
	SessionExpired     ErrorCode = "session_expired"
	StorageUnavailable ErrorCode = "storage_unavailable"
	Unauthorized       ErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case InputTooLarge:
		return true
	case InternalError:
		return true
	case InvalidDraft:
		return true
	case InvalidRequest:
		return true
	case OperationConflict:
		return true
	case OperationUnknown:
		return true
	case ProfileDisabled:
		return true
	case ProtocolMismatch:
		return true
	case ResourceNotFound:
		return true
	case RevisionConflict:
		return true
	case RunBusy:
		return true
	case ServiceUnavailable:
		return true
	case SessionExpired:
		return true
	case StorageUnavailable:
		return true
	case Unauthorized:
		return true
	default:
		return false
	}
}

// Defines values for LimitsCanvasBytes.
const (
	N262144 LimitsCanvasBytes = 262144
)

// Valid indicates whether the value is a known member of the LimitsCanvasBytes enum.
func (e LimitsCanvasBytes) Valid() bool {
	switch e {
	case N262144:
		return true
	default:
		return false
	}
}

// Defines values for LimitsEditorTtlSeconds.
const (
	N300 LimitsEditorTtlSeconds = 300
)

// Valid indicates whether the value is a known member of the LimitsEditorTtlSeconds enum.
func (e LimitsEditorTtlSeconds) Valid() bool {
	switch e {
	case N300:
		return true
	default:
		return false
	}
}

// Defines values for LimitsExecutionBudgetSeconds.
const (
	N30 LimitsExecutionBudgetSeconds = 30
)

// Valid indicates whether the value is a known member of the LimitsExecutionBudgetSeconds enum.
func (e LimitsExecutionBudgetSeconds) Valid() bool {
	switch e {
	case N30:
		return true
	default:
		return false
	}
}

// Defines values for LimitsInputBytes.
const (
	N4096 LimitsInputBytes = 4096
)

// Valid indicates whether the value is a known member of the LimitsInputBytes enum.
func (e LimitsInputBytes) Valid() bool {
	switch e {
	case N4096:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMaxActiveRuns.
const (
	LimitsMaxActiveRunsN1 LimitsMaxActiveRuns = 1
)

// Valid indicates whether the value is a known member of the LimitsMaxActiveRuns enum.
func (e LimitsMaxActiveRuns) Valid() bool {
	switch e {
	case LimitsMaxActiveRunsN1:
		return true
	default:
		return false
	}
}

// Defines values for LimitsMessageBytes.
const (
	N524288 LimitsMessageBytes = 524288
)

// Valid indicates whether the value is a known member of the LimitsMessageBytes enum.
func (e LimitsMessageBytes) Valid() bool {
	switch e {
	case N524288:
		return true
	default:
		return false
	}
}

// Defines values for LimitsOutputBytes.
const (
	N5120 LimitsOutputBytes = 5120
)

// Valid indicates whether the value is a known member of the LimitsOutputBytes enum.
func (e LimitsOutputBytes) Valid() bool {
	switch e {
	case N5120:
		return true
	default:
		return false
	}
}

// Defines values for LimitsPrefixBytes.
const (
	N1024 LimitsPrefixBytes = 1024
)

// Valid indicates whether the value is a known member of the LimitsPrefixBytes enum.
func (e LimitsPrefixBytes) Valid() bool {
	switch e {
	case N1024:
		return true
	default:
		return false
	}
}

// Defines values for OperationKind.
const (
	OperationKindCreate  OperationKind = "create"
	OperationKindPublish OperationKind = "publish"
	OperationKindRun     OperationKind = "run"
	OperationKindSave    OperationKind = "save"
	OperationKindTest    OperationKind = "test"
)

// Valid indicates whether the value is a known member of the OperationKind enum.
func (e OperationKind) Valid() bool {
	switch e {
	case OperationKindCreate:
		return true
	case OperationKindPublish:
		return true
	case OperationKindRun:
		return true
	case OperationKindSave:
		return true
	case OperationKindTest:
		return true
	default:
		return false
	}
}

// Defines values for OperationPhase.
const (
	Completed OperationPhase = "completed"
	Recorded  OperationPhase = "recorded"
	Rejected  OperationPhase = "rejected"
	Unknown   OperationPhase = "unknown"
)

// Valid indicates whether the value is a known member of the OperationPhase enum.
func (e OperationPhase) Valid() bool {
	switch e {
	case Completed:
		return true
	case Recorded:
		return true
	case Rejected:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for RunMode.
const (
	Debug   RunMode = "debug"
	Release RunMode = "release"
)

// Valid indicates whether the value is a known member of the RunMode enum.
func (e RunMode) Valid() bool {
	switch e {
	case Debug:
		return true
	case Release:
		return true
	default:
		return false
	}
}

// Defines values for RunQueryKind.
const (
	RunQueryKindHistory   RunQueryKind = "history"
	RunQueryKindOperation RunQueryKind = "operation"
	RunQueryKindRun       RunQueryKind = "run"
)

// Valid indicates whether the value is a known member of the RunQueryKind enum.
func (e RunQueryKind) Valid() bool {
	switch e {
	case RunQueryKindHistory:
		return true
	case RunQueryKindOperation:
		return true
	case RunQueryKindRun:
		return true
	default:
		return false
	}
}

// Defines values for ServiceStatusProtocolVersion.
const (
	N1 ServiceStatusProtocolVersion = 1
)

// Valid indicates whether the value is a known member of the ServiceStatusProtocolVersion enum.
func (e ServiceStatusProtocolVersion) Valid() bool {
	switch e {
	case N1:
		return true
	default:
		return false
	}
}

// Defines values for ServiceStatusState.
const (
	Disabled    ServiceStatusState = "disabled"
	Ready       ServiceStatusState = "ready"
	Unavailable ServiceStatusState = "unavailable"
)

// Valid indicates whether the value is a known member of the ServiceStatusState enum.
func (e ServiceStatusState) Valid() bool {
	switch e {
	case Disabled:
		return true
	case Ready:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// Bootstrap defines model for Bootstrap.
type Bootstrap struct {
	Limits    Limits               `json:"limits"`
	NodeTypes []BootstrapNodeTypes `json:"node_types"`
	Principal Principal            `json:"principal"`

	// Workflow Coze-owned graph and revision. Canvas is native JSON text; safe incomplete drafts may be saved. IDs are opaque strings, including decimal Coze IDs, never JS numbers.
	Workflow Workflow `json:"workflow"`
}

// BootstrapNodeTypes defines model for Bootstrap.NodeTypes.
type BootstrapNodeTypes int64

// CloseResult defines model for CloseResult.
type CloseResult struct {
	Closed bool `json:"closed"`
}

// CreateInput defines model for CreateInput.
type CreateInput struct {
	Name string `json:"name"`
}

// CreateRequest defines model for CreateRequest.
type CreateRequest struct {
	Name        string      `json:"name"`
	OperationId OperationId `json:"operation_id"`
}

// EditorCloseInput defines model for EditorCloseInput.
type EditorCloseInput struct {
	BridgeId Identifier `json:"bridge_id"`
}

// EditorExchangeInput Native generates write operation IDs. operation_id input is only a read_operation lookup. No actor, secret, URL, headers or arbitrary command.
type EditorExchangeInput struct {
	BridgeId            Identifier                         `json:"bridge_id"`
	Canvas              *string                            `json:"canvas,omitempty"`
	ExpectedRevision    *Identifier                        `json:"expected_revision,omitempty"`
	Generation          int64                              `json:"generation"`
	Input               *TextInput                         `json:"input,omitempty"`
	Name                *string                            `json:"name,omitempty"`
	Operation           EditorOperation                    `json:"operation"`
	OperationId         *OperationId                       `json:"operation_id,omitempty"`
	ProtocolVersion     EditorExchangeInputProtocolVersion `json:"protocol_version"`
	RequestId           Identifier                         `json:"request_id"`
	RunId               *Identifier                        `json:"run_id,omitempty"`
	SuccessfulTestRunId *Identifier                        `json:"successful_test_run_id,omitempty"`
}

// EditorExchangeInputProtocolVersion defines model for EditorExchangeInput.ProtocolVersion.
type EditorExchangeInputProtocolVersion int64

// EditorExchangeResult defines model for EditorExchangeResult.
type EditorExchangeResult struct {
	Bootstrap   *Bootstrap   `json:"bootstrap,omitempty"`
	OperationId *OperationId `json:"operation_id,omitempty"`

	// Receipt Dispatch receipt, not engine status. completed identifies committed resource/execution registration, not successful workflow execution.
	Receipt   *OperationReceipt `json:"receipt,omitempty"`
	RequestId Identifier        `json:"request_id"`
	Run       *Run              `json:"run,omitempty"`

	// Workflow Coze-owned graph and revision. Canvas is native JSON text; safe incomplete drafts may be saved. IDs are opaque strings, including decimal Coze IDs, never JS numbers.
	Workflow *Workflow `json:"workflow,omitempty"`
}

// EditorOpenRequest defines model for EditorOpenRequest.
type EditorOpenRequest struct {
	WorkflowId Identifier `json:"workflow_id"`
}

// EditorOpenedView defines model for EditorOpenedView.
type EditorOpenedView struct {
	BridgeId        Identifier                      `json:"bridge_id"`
	ExpiresAtMs     int64                           `json:"expires_at_ms"`
	Generation      int64                           `json:"generation"`
	ProtocolVersion EditorOpenedViewProtocolVersion `json:"protocol_version"`

	// Workflow Coze-owned graph and revision. Canvas is native JSON text; safe incomplete drafts may be saved. IDs are opaque strings, including decimal Coze IDs, never JS numbers.
	Workflow Workflow `json:"workflow"`
}

// EditorOpenedViewProtocolVersion defines model for EditorOpenedView.ProtocolVersion.
type EditorOpenedViewProtocolVersion int64

// EditorOperation defines model for EditorOperation.
type EditorOperation string

// EditorSessionSecret defines model for EditorSessionSecret.
type EditorSessionSecret struct {
	ExpiresAtMs int64    `json:"expires_at_ms"`
	RunEpoch    RunEpoch `json:"run_epoch"`

	// Secret Native/API only. Never serialize this response to renderer, URL, log or MessageChannel.
	Secret     string     `json:"secret"`
	SessionId  Identifier `json:"session_id"`
	WorkflowId Identifier `json:"workflow_id"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code        ErrorCode    `json:"code"`
	Message     string       `json:"message"`
	OperationId *OperationId `json:"operation_id,omitempty"`
}

// Identifier defines model for Identifier.
type Identifier = string

// Limits defines model for Limits.
type Limits struct {
	CanvasBytes            LimitsCanvasBytes            `json:"canvas_bytes"`
	EditorTtlSeconds       LimitsEditorTtlSeconds       `json:"editor_ttl_seconds"`
	ExecutionBudgetSeconds LimitsExecutionBudgetSeconds `json:"execution_budget_seconds"`
	InputBytes             LimitsInputBytes             `json:"input_bytes"`
	MaxActiveRuns          LimitsMaxActiveRuns          `json:"max_active_runs"`
	MessageBytes           LimitsMessageBytes           `json:"message_bytes"`
	OutputBytes            LimitsOutputBytes            `json:"output_bytes"`
	PrefixBytes            LimitsPrefixBytes            `json:"prefix_bytes"`
}

// LimitsCanvasBytes defines model for Limits.CanvasBytes.
type LimitsCanvasBytes int64

// LimitsEditorTtlSeconds defines model for Limits.EditorTtlSeconds.
type LimitsEditorTtlSeconds int64

// LimitsExecutionBudgetSeconds defines model for Limits.ExecutionBudgetSeconds.
type LimitsExecutionBudgetSeconds int64

// LimitsInputBytes defines model for Limits.InputBytes.
type LimitsInputBytes int64

// LimitsMaxActiveRuns defines model for Limits.MaxActiveRuns.
type LimitsMaxActiveRuns int64

// LimitsMessageBytes defines model for Limits.MessageBytes.
type LimitsMessageBytes int64

// LimitsOutputBytes defines model for Limits.OutputBytes.
type LimitsOutputBytes int64

// LimitsPrefixBytes defines model for Limits.PrefixBytes.
type LimitsPrefixBytes int64

// ListRequest defines model for ListRequest.
type ListRequest struct {
	Cursor *string `json:"cursor,omitempty"`
	Limit  *int64  `json:"limit,omitempty"`
}

// NodeResult defines model for NodeResult.
type NodeResult struct {
	Error  *ErrorResponse `json:"error,omitempty"`
	NodeId Identifier     `json:"node_id"`
	Output *string        `json:"output,omitempty"`
	State  string         `json:"state"`
}

// OperationId defines model for OperationId.
type OperationId = string

// OperationKind defines model for OperationKind.
type OperationKind string

// OperationPhase defines model for OperationPhase.
type OperationPhase string

// OperationReceipt Dispatch receipt, not engine status. completed identifies committed resource/execution registration, not successful workflow execution.
type OperationReceipt struct {
	Error       *ErrorResponse `json:"error,omitempty"`
	Kind        OperationKind  `json:"kind"`
	OperationId OperationId    `json:"operation_id"`
	Phase       OperationPhase `json:"phase"`
	Revision    *Identifier    `json:"revision,omitempty"`
	RunId       *Identifier    `json:"run_id,omitempty"`
	Version     *Version       `json:"version,omitempty"`
	WorkflowId  *Identifier    `json:"workflow_id,omitempty"`
}

// Principal defines model for Principal.
type Principal struct {
	OwnerId  Identifier `json:"owner_id"`
	SpaceId  Identifier `json:"space_id"`
	TenantId Identifier `json:"tenant_id"`
	UserId   Identifier `json:"user_id"`
}

// PublishRequest defines model for PublishRequest.
type PublishRequest struct {
	ExpectedRevision    Identifier  `json:"expected_revision"`
	OperationId         OperationId `json:"operation_id"`
	SuccessfulTestRunId Identifier  `json:"successful_test_run_id"`
}

// Run defines model for Run.
type Run struct {
	Error        *ErrorResponse `json:"error,omitempty"`
	FinishedAtMs *int64         `json:"finished_at_ms,omitempty"`
	Input        *TextInput     `json:"input,omitempty"`
	Mode         RunMode        `json:"mode"`
	Nodes        *[]NodeResult  `json:"nodes,omitempty"`
	OperationId  OperationId    `json:"operation_id"`
	Output       *string        `json:"output,omitempty"`
	Revision     *Identifier    `json:"revision,omitempty"`
	RunId        Identifier     `json:"run_id"`
	StartedAtMs  int64          `json:"started_at_ms"`

	// State Actual engine status; new values stay visible and never imply success.
	State      string     `json:"state"`
	Terminal   bool       `json:"terminal"`
	Version    *Version   `json:"version,omitempty"`
	WorkflowId Identifier `json:"workflow_id"`
}

// RunEpoch defines model for RunEpoch.
type RunEpoch = OperationId

// RunInput defines model for RunInput.
type RunInput struct {
	Input      TextInput  `json:"input"`
	Version    Version    `json:"version"`
	WorkflowId Identifier `json:"workflow_id"`
}

// RunList defines model for RunList.
type RunList struct {
	Items      []RunSummary `json:"items"`
	NextCursor *string      `json:"next_cursor,omitempty"`
}

// RunMode defines model for RunMode.
type RunMode string

// RunQueryInput defines model for RunQueryInput.
type RunQueryInput struct {
	Cursor      *string      `json:"cursor,omitempty"`
	Kind        RunQueryKind `json:"kind"`
	Limit       *int64       `json:"limit,omitempty"`
	OperationId *OperationId `json:"operation_id,omitempty"`
	RunId       *Identifier  `json:"run_id,omitempty"`
	WorkflowId  *Identifier  `json:"workflow_id,omitempty"`
}

// RunQueryKind defines model for RunQueryKind.
type RunQueryKind string

// RunQueryResult defines model for RunQueryResult.
type RunQueryResult struct {
	History *RunList `json:"history,omitempty"`

	// Receipt Dispatch receipt, not engine status. completed identifies committed resource/execution registration, not successful workflow execution.
	Receipt *OperationReceipt `json:"receipt,omitempty"`
	Run     *Run              `json:"run,omitempty"`
}

// RunRequest defines model for RunRequest.
type RunRequest struct {
	Input       TextInput   `json:"input"`
	OperationId OperationId `json:"operation_id"`
	Version     Version     `json:"version"`
}

// RunSummary Bounded list summary; read the detail endpoint for full content.
type RunSummary struct {
	Error        *ErrorResponse `json:"error,omitempty"`
	FinishedAtMs *int64         `json:"finished_at_ms,omitempty"`
	Mode         RunMode        `json:"mode"`
	OperationId  OperationId    `json:"operation_id"`
	Revision     *Identifier    `json:"revision,omitempty"`
	RunId        Identifier     `json:"run_id"`
	StartedAtMs  int64          `json:"started_at_ms"`

	// State Actual engine status; new values stay visible and never imply success.
	State      string     `json:"state"`
	Terminal   bool       `json:"terminal"`
	Version    *Version   `json:"version,omitempty"`
	WorkflowId Identifier `json:"workflow_id"`
}

// SaveRequest defines model for SaveRequest.
type SaveRequest struct {
	Canvas           string      `json:"canvas"`
	ExpectedRevision Identifier  `json:"expected_revision"`
	Name             string      `json:"name"`
	OperationId      OperationId `json:"operation_id"`
}

// ServiceStatus defines model for ServiceStatus.
type ServiceStatus struct {
	Limits          Limits                       `json:"limits"`
	ProtocolVersion ServiceStatusProtocolVersion `json:"protocol_version"`
	Ready           bool                         `json:"ready"`
	RunEpoch        RunEpoch                     `json:"run_epoch"`
	State           ServiceStatusState           `json:"state"`
}

// ServiceStatusProtocolVersion defines model for ServiceStatus.ProtocolVersion.
type ServiceStatusProtocolVersion int64

// ServiceStatusState defines model for ServiceStatus.State.
type ServiceStatusState string

// TestRequest defines model for TestRequest.
type TestRequest struct {
	ExpectedRevision Identifier  `json:"expected_revision"`
	Input            TextInput   `json:"input"`
	OperationId      OperationId `json:"operation_id"`
}

// TextInput defines model for TextInput.
type TextInput struct {
	Input string `json:"input"`
}

// Version defines model for Version.
type Version = string

// Workflow Coze-owned graph and revision. Canvas is native JSON text; safe incomplete drafts may be saved. IDs are opaque strings, including decimal Coze IDs, never JS numbers.
type Workflow struct {
	Canvas           string     `json:"canvas"`
	Name             string     `json:"name"`
	PublishedVersion *Version   `json:"published_version,omitempty"`
	Revision         Identifier `json:"revision"`
	Runnable         bool       `json:"runnable"`
	UpdatedAtMs      int64      `json:"updated_at_ms"`
	WorkflowId       Identifier `json:"workflow_id"`
}

// WorkflowList defines model for WorkflowList.
type WorkflowList struct {
	Items      []WorkflowSummary `json:"items"`
	NextCursor *string           `json:"next_cursor,omitempty"`
}

// WorkflowSummary Bounded list summary; read the detail endpoint for full content.
type WorkflowSummary struct {
	Name             string     `json:"name"`
	PublishedVersion *Version   `json:"published_version,omitempty"`
	Revision         Identifier `json:"revision"`
	Runnable         bool       `json:"runnable"`
	UpdatedAtMs      int64      `json:"updated_at_ms"`
	WorkflowId       Identifier `json:"workflow_id"`
}

// serviceBearerContextKey is the context key for ServiceBearer security scheme
type serviceBearerContextKey string

// OpenEditorSessionParams defines parameters for OpenEditorSession.
type OpenEditorSessionParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// CloseEditorSessionParams defines parameters for CloseEditorSession.
type CloseEditorSessionParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// ReadWorkflowOperationParams defines parameters for ReadWorkflowOperation.
type ReadWorkflowOperationParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// EnsureLocalPrincipalParams defines parameters for EnsureLocalPrincipal.
type EnsureLocalPrincipalParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// GetWorkflowStatusParams defines parameters for GetWorkflowStatus.
type GetWorkflowStatusParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// ListWorkflowsParams defines parameters for ListWorkflows.
type ListWorkflowsParams struct {
	Cursor         *string  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit          *int64   `form:"limit,omitempty" json:"limit,omitempty"`
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// CreateWorkflowParams defines parameters for CreateWorkflow.
type CreateWorkflowParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// ReadWorkflowParams defines parameters for ReadWorkflow.
type ReadWorkflowParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// SaveWorkflowParams defines parameters for SaveWorkflow.
type SaveWorkflowParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`

	// XYijieEditorSession Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze.
	XYijieEditorSession string `json:"X-Yijie-Editor-Session"`
}

// GetEditorBootstrapParams defines parameters for GetEditorBootstrap.
type GetEditorBootstrapParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`

	// XYijieEditorSession Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze.
	XYijieEditorSession string `json:"X-Yijie-Editor-Session"`
}

// ListWorkflowRunsParams defines parameters for ListWorkflowRuns.
type ListWorkflowRunsParams struct {
	Cursor         *string  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit          *int64   `form:"limit,omitempty" json:"limit,omitempty"`
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// RunWorkflowParams defines parameters for RunWorkflow.
type RunWorkflowParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// ReadWorkflowRunParams defines parameters for ReadWorkflowRun.
type ReadWorkflowRunParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`
}

// TestWorkflowParams defines parameters for TestWorkflow.
type TestWorkflowParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`

	// XYijieEditorSession Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze.
	XYijieEditorSession string `json:"X-Yijie-Editor-Session"`
}

// PublishWorkflowParams defines parameters for PublishWorkflow.
type PublishWorkflowParams struct {
	XYijieRunEpoch RunEpoch `json:"X-Yijie-Run-Epoch"`

	// XYijieEditorSession Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze.
	XYijieEditorSession string `json:"X-Yijie-Editor-Session"`
}

// OpenEditorSessionJSONRequestBody defines body for OpenEditorSession for application/json ContentType.
type OpenEditorSessionJSONRequestBody = EditorOpenRequest

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody = CreateRequest

// SaveWorkflowJSONRequestBody defines body for SaveWorkflow for application/json ContentType.
type SaveWorkflowJSONRequestBody = SaveRequest

// RunWorkflowJSONRequestBody defines body for RunWorkflow for application/json ContentType.
type RunWorkflowJSONRequestBody = RunRequest

// TestWorkflowJSONRequestBody defines body for TestWorkflow for application/json ContentType.
type TestWorkflowJSONRequestBody = TestRequest

// PublishWorkflowJSONRequestBody defines body for PublishWorkflow for application/json ContentType.
type PublishWorkflowJSONRequestBody = PublishRequest
